const jobs = [
  {
    "role": "Senior Data Engineer ",
    "employer": "Spexture",
    "start": "Wed Aug 14 2024 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "CURRENT_DATE",
    "z-index": "1",
    "css name": "darkspring",
    "css RGB": "#118811",
    "text color": "#000000",
    "Description": "• Implementing end-to-end MLOps CI/CD pipeline with target-based design\n• Hashicorp Terraform and Vault for multi-environment infrastructure and credentials\n• GitHub Actions for CI/CD and Argo CD for change detection\n• Kubernetes for orchestrating PySparkSQL Docker containers running on an EKS-managed cluster.\n• Amazon SageMaker for ML model integration, real-time scoring, and model versioning\n• Amazon Managed Grafana for real-time visualization\n• PySpark and PySpark SQL for data quality validation, data cleaning, and feature engineering \n• AWS Glue for metadata tagging, tracking versioning/lineage, and enforcing governance"
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Fannie Mae",
    "start": "Fri Feb 16 2024 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Wed Jun 26 2024 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "2",
    "css name": "darkcyan",
    "css RGB": "#006900",
    "text color": "#FFFFFF",
    "Description": "• Extensive work with SQL, AWS Redshift, Glue, Airflow, S3, IAM, Lambda, REST, SNS, and dbt\n• Created dbt-validated SQL code for data cleansing and data lake ingestion \n• Used Amazon Glue to track schema changes and revise Redshift external views\n• Created custom views required for analysis and reporting in Redshift\n• Documented processes to build, test, and deploy data pipeline components for in-house ETL framework"
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "The Cigna Group",
    "start": "Sun Apr 30 2023 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Sat Dec 16 2023 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "3",
    "css name": "darkcyan",
    "css RGB": "#006688",
    "text color": "#FFFFFF",
    "Description": "• As a senior data engineer in the data cyber security team of the [Cigna Group](http://www.thecignagroup.com) created a [REST API] using [Postman], [Bash], [Linux], and [OpenAPI] for pulling credentials from [CyberArk](http://www.cyberark.com) using [OpenSSL] with [mutual TLS SSL authentication](http://docs.solace.com/Security/Two-Way-SSL-Authentication.htm) via [API Gateway]. \n•  Migrated a suite of legacy [ETL][data pipeline] [Python] elements running on the [Unity IoC platform] with [PostgreSQL] and [S3] to pull credentials from the [CyberArk] identity service at runtime rather than using [Fernet](http://cryptography.io/en/latest/fernet/) encrypted local files. \n•  Upgraded [GitHub] apps to use [Jenkins](http://docs.aws.amazon.com/apigateway/) [CI/CD pipeline] for build, applying software and cyber-security code checks, and on-prem server installation."
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Warner Brothers",
    "start": "Wed Aug 31 2022 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Sun Apr 30 2023 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "2",
    "css name": "blue",
    "css RGB": "#0000ff",
    "text color": "#FFFFFF",
    "Description": "• As a senior data engineer in the analytics team of [Warner Brothers](http://warnerbrosgames.com) Division, implemented high-volume [ETL] [data pipeline] [integrations] transforming and sharing  game telemetry and [user PII data] between WB-distributed consumer games and [marketing service platforms] via [Segment customer data platform](http://segment.com/customer-data-platform/) using [Kafka](http://aws.amazon.com/msk/), [Amazon S3], [Redshift](http://aws.amazon.com/redshift/), and [Apache Airflow](http://airflow.apache.org). \n• Employed [Python], [GitHub], [Bash], [Linux], [Amazon Glue](http://aws.amazon.com/glue/) and [Apache Airflow](http://airflow.apache.org) for external [3rd-party integrations] and internal dev-ops integrations with [Jenkins], [PostgreSQL], [DataDog](http://www.datadoghq.com),  [ZenDesk](http://zendesk.com). and [Tableau].\n• Integrated with [Google BigQuery](https://cloud.google.com/bigquery using  [Apache Airflow](http://aws.amazon.com/managed-workflows-for-apache-airflow/), [Amazon S3], and [Redshift](http://aws.amazon.com/redshift/)."
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Angel Studios ",
    "start": "Sun Oct 31 2021 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Wed Aug 31 2022 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "1",
    "css name": "mediumblue",
    "css RGB": "#4400cd",
    "text color": "#FFFFFF",
    "Description": "• Senior data engineer for [Angel Studios](http://www.angel.com/home), a streaming media service that offers family-friendly entertainment that amplifies light, with titles including The Chosen, Dry Bar Comedy, and Tuttle Twins.\n• Used [Python], [GitHub], [Pandas], [Numpy], [Keras], [Bash], [Linux], [PostgreSQL], and [Jupyter](http://jupyter.org) to build and tune hyperparameters of a [convolutional neural network](http://towardsdatascience.com/a-comprehensive-guide-to-convolutional-neural-networks-the-eli5-way-3bd2b1164a53) with [supervised learning] on [Amazon Sagemaker](http://aws.amazon.com/pm/sagemaker/) to classify movie frames from episodic programs stored in [Amazon S3](http://aws.amazon.com/s3/storage-classes). \n• Built web client apps using [Python] with [Postman](http://www.postman.com) that made [REST] requests to pull monthly usage data from various web marketing partners like [FaceBook Marketing], [Google Play](http://play.google/howplayworks/) , and [Vimeo](http://vimeo.com). \n• Worked with [Segment customer data platform](http://segment.com/customer-data-platform/), [Excel], and [Tableau] to create scheduled reports for the company's sales and finance teams."
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Data Laboratory",
    "start": "Sat Oct 31 2020 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Sun Oct 31 2021 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "2",
    "css name": "blueviolet",
    "css RGB": "#8a2be2",
    "text color": "#FFFFFF",
    "Description": "• As a senior software engineer for Data Laboratory, an internet company that provides daily lead reports for independent real-estage agents world-wide, I  [containerized] legacy web applications using [Bash], [Linux], [GitHub], [Docker](http://www.docker.com) and [Amazon Secrets Manager](http://aws.amazon.com/secrets-manager/). \n• Updated legacy web apps using [Bash], [Linux], [HTML], [CSS], [JavaScript], [PostgreSQL], [NGINX], and [OpenSSL].\n• Documented existing data architecture as [ERDs](http://www.lucidchart.com/pages/er-diagrams) using [DBeaver Enterprise](http://dbeaver.com/dbeaver-enterprise/). "
  },
  {
    "role": "Senior Full-Stack Developer ",
    "employer": "NuSkin",
    "start": "Thu Oct 31 2019 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Sat Oct 31 2020 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "1",
    "css name": "purple",
    "css RGB": "#800080",
    "text color": "#FFFFFF",
    "Description": "• As a senior full stack developer for [NuSkin](https://www.nuskin.com/us/en/, an international company known for its excellent  skin and beauty products I created new [Vue.js](http://vuejs.org), [Nuxt](http://nuxt.com), and [Vuetify](http://vuetifyjs.com/en/) components using [Bash], [Linux], [GitHub], [NodeJS], [HTML] and [CSS].  \n• Internationalized content using [Adobe Experience Cloud](business.adobe.com/)."
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "SeniorLink",
    "start": "Tue Feb 28 2017 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Thu Oct 31 2019 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "2",
    "css name": "maroon",
    "css RGB": "#800000",
    "text color": "#FFFFFF",
    "Description": "• As a senior data engineer for SeniorLink's [Vela project]{/static_content/portfolio/Vela-150x126.png} a homeservices support platform, helped create [ETL](http://aws.amazon.com/what-is/etl/) processes using [Amazon Kinesis](http://aws.amazon.com/pm/kinesis/), [Python], [PySpark](http://spark.apache.org), and [Amazon Data Pipeline](http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/what-is-datapipeline.html) to load structured event data from [PostgreSQL] databases into [Redshift](http://aws.amazon.com/pm/redshift/). \n• Saved data to [Amazon S3] using [Amazon Kinesis] and triggered [Amazon Lambda](http://docs.aws.amazon.com/lambda/) jobs to aggregate steaming event data into [schema-on-read] file formats, [Apache Avro](http://avro.apache.org) and [Apache Parquet](http://parquet.apache.org).\n• Steered efforts in creating a [Data Lake](http://aws.amazon.com/big-data/datalakes-and-analytics/datalakes/) using [PostgreSQL] and [FlyWay](http://flywaydb.org) with [Python] and [PySpark](http://spark.apache.org/docs/latest/api/python/index.html) pre-processing on [EC2 instances] using shared [Amazon EFS](http://zesty.co/blog/ebs-vs-efs-which-is-right) for staged storage.\n• Used streaming event messages queued in [RabbitMQ](http://docs.aws.amazon.com/amazon-mq/latest/developer-guide/working-with-rabbitmq.html) and [Amazon Kinesis] to build [type-2 slowly changing dimensions] and accumulative facts tables. \n• Designed and implemented a custom [star-schema warehouse](http://www.databricks.com/glossary/star-schema) and [ETL] processes to [de-normalize](http://en.wikipedia.org/wiki/Denormalization) and load data into [Redshift](http://aws.amazon.com/redshift/) data warehouse for BI reporting using [Tableau](http://www.tableau.com).\n• [Test-driven development](http://www.pluralsight.com/blog/software-development/tdd-vs-bdd) using [Bash], [Linux], [Python], [PyCharm], [PyTest], [Unit-test], [GitHub], [Jira], and [Jenkins](http://www.jenkins.io/)."
  },
  {
    "role": "Senior Back-End Engineer ",
    "employer": "BigR.io",
    "start": "Wed Nov 30 2016 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Tue Feb 28 2017 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "1",
    "css name": "crimson",
    "css RGB": "#dc143c",
    "text color": "#FFFFFF",
    "Description": "• As a senior software engineer at [BigR.io]{/static_content/portfolio/Bigr.io_-150x106.png} I used [Amazon microservices] for custom voice-based [natural language processing] applications.\n• Used [Apache ActiveMQ](http://activemq.apache.org), [Swagger](http://swagger.io/), [JSON], [Jackson](http://url.com), [AOP](https://www.baeldung.com/spring-aop), [Eclipse], [Maven], [GitHub], [Jira], [PostgreSQL], and [Jenkins].\n• [Java], [J2EE], [Servlets], [Spring], [SpringBoot], [JAX-RS], [Bash], [Linux], [JUnit], [JMeter], and [JProfile]"
  },
  {
    "role": "Technical Lead / Co-Founder ",
    "employer": "ClipFile LLC",
    "start": "Mon Jan 31 2011 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Wed Nov 30 2016 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "2",
    "css name": "orangered",
    "css RGB": "#ff4500",
    "text color": "#000000",
    "Description": "• Co-founded [ClipFile]{/static_content/portfolio/clipfile-infrastructure-150x150.png}, a company that envisioned building a web destination where users could easily record and share their favorite pieces of content like facts, authored stories, quotes, articles, chapters, or personal thoughts, as a way of concretely defining their personal [mindset]{https://sourcesofinsight.com/wp-content/uploads/2014/04/Mindset-768x505.jpg}(http://sourcesofinsight.com/what-is-mindset/).\n• Implemented [fuzzy matching](http://nanonets.com/blog/fuzzy-matching-fuzzy-logic/), [word clustering](http://www.ilc.cnr.it/EAGLES96/rep2/node37.html#:~:text=Word%20clustering%20is%20a%20technique,to%20information%20retrieval%20and%20filtering.), [semantic similarity scores], and [collaborative filtering] to help users find content that matched or differed from thieir own mindset.\n• Launched a novel [SaaS] using [Amazon Web Services] that let individuals and content creators search and share mindsets.\n• Conceptualized patented technology by designing and implementing a fuil-stack consumer-facing content management system that supported tuned matching among selected attributes.\n• [Java], [J2EE], [JSP], [Servlets], [Spring], [Amazon services], [JavaScript], [JQuery], [HTML], [CSS], [JUnit], [JMeter], [JProfile].\n• Utilized [REST], [Swagger], [Apache Shiro](http://shiro.apache.org), [Eclipse IDE](http://www.eclipse.org/home/whatis/), [Apache Maven](http://maven.apache.org/what-is-maven.html), [Apache Ant](http://ant.apache.org), [GitHub], [Hibernate], [Amazon SimpleDB](http://aws.amazon.com/simpledb/), [Linux](http://www.centos.org), [Apache Tomcat](http://tomcat.apache.org), [Bash], [Linux], [Jetty](http://projects.eclipse.org/projects/rt.jetty), and [Spring MVC](http://docs.spring.io/spring-framework/reference/web/webmvc.html).\n• Served as co-founder and co-authored [four patents](http://www.freepatentsonline.com/y2013/0325870.html)."
  },
  {
    "role": "Lead Solutions Architect / Co-Founder ",
    "employer": "Sierra Vista Group LLC",
    "start": "Thu Oct 31 2002 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Mon Jan 31 2011 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "1",
    "css name": "orange",
    "css RGB": "#ffa500",
    "text color": "#000000",
    "Description": "• Co-founded a finance and technology boutique called [Sierra Vista Group] that delivered support in planning and proposing effective IT strategies for key clients in several industries. \n• Performed various services, including system and architecture assessment and solutions design, to ensure the smooth running of technical projects.\n• Managed project schedules and technical specifications to match business requirements within contractual budget constraints. \n• Identified opportunities for potential clients requiring expertise in product development, software engineering, and data modeling. Negotiated and communicated with c-level client management regarding project milestone agreements.\n• Increased ROI for each client’s project by hiring and managing contractors to deliver custom software solutions.\n• Delivered high-level leadership and guidance to a team of software engineering consultants for several projects to accelerate operational excellence."
  },
  {
    "role": "Technical Lead / Co-Founder ",
    "employer": "HomePorfolio LLC ",
    "start": "Sat Jan 31 1998 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Thu Oct 31 2002 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "1",
    "css name": "teal",
    "css RGB": "#008080",
    "text color": "#FFFFFF",
    "Description": "• As co-founder and CTO, designed and led the development of a public website used by discerning home designers and builders called [HomePortfolio]. \n• Hired a staff of  10 software and databases developers. \n• Worked with data acquisition team to scan and tag over 700,000 premium home design products from over 2,000 manufactures and vendors.\n• Designed datamodel and data entry tools for category-specific product attribution. \n• Helped extended the business model to provide online product selection tools for participating vendors and manufacturers.\n• Instrumental in raising over $70M in venture capital. \n• Used [Oracle], [ATG Dyanamo]( https://docs.oracle.com/cd/E24152_01/Platform.10-1/ATGPersBusinessGuide/html/s0102dynamoapplicationframework01.html), [Java], [Akamai]{https://www.hiclipart.com/free-transparent-background-png-clipart-zkmsn}(www.akamai.com/), [WebTrends](http://www.webtrends.com), [FileMakerPro], [ImageMagik](imagemagick.org/index.php), [Bash], [Linux], [HTML], [JavaScript], [CSS], and [Omnigraffle](http://www.omnigroup.com/omnigraffle) for data modeling and workflow designs."
  },
  {
    "role": "Lead Software Developer ",
    "employer": "BuildingBlocks LLC ",
    "start": "Fri May 31 1996 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Sat Jan 31 1998 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "1",
    "css name": "darkcyan",
    "css RGB": "#008b8b",
    "text color": "#FFFFFF",
    "Description": "• As lead software developer, built a CD-ROM-based home design application for selecting premium home design products for previewing in the context of images of any household rooms. \n• Built the prototype using Adobe Photoshop and [Macromedia Director](http://macromedia.fandom.com/wiki/Macromedia_Director).\n• Built the actual application using using [Bash], [Linux], [Java] and [Marimba Bongo](http://www.thriftbooks.com/w/official-marimba-guide-to-bongo_danny-goodman/2574616/#edition=58026223&idiq=42367912) widget layout tool.\n• Updates for the self-updating application were delivered over the internet using [Marimba Castanet](http://www.infoworld.com/article/2076707/marimba-launches-new-castanet-with-a-less-java-centric-focus.html) push-technology."
  },
  {
    "role": "Ph.D. Media Arts & Science",
    "employer": "MIT Media Lab",
    "start": "Fri Aug 31 1990 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Mon Mar 31 1997 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "2",
    "css name": "blue",
    "css RGB": "#0000ff",
    "text color": "#FFFFFF",
    "Description": "•\tDoctor of Philosopy degree, [MIT]{/static_content/portfolio/MIT-logo.png}, Cambridge, Massachusettes\n•\tMedia Laboratory, Media Arts and Sciences\n•\tTook courses in machine vision, signals and systems, digital signal processing, and stochastics.\n•\tHelped build the operating system for the [Cheops multi-processor system](http://alumni.media.mit.edu/~wad/cheops_CSVT/cheops.html) used for digital video research and for holographic video\n•\t[“Vision-assisted modeling for model-based video representations”](http://dspace.mit.edu/handle/1721.1/29123), (Ph.D. Dissertation) MIT, Program in Media Arts & Sciences, 1997\n•\t[“Semiautomatic 3-D Model Extraction from Uncalibrated 2-D Camera Views.”](http://www.media.mit.edu/publications/semiautomatic-3-d-model-extraction-from-uncalibrated-2-d-camera-views-2/) S. Becker & V. M. Bove, Jr., Proc. SPIE Image Synthesis, 2410, 1995, pp. 447-461.\n•\t“Semiautomatic Scene Modeling From 2-D Views with Partially Known Structure.” Shawn Becker, MIT Media Lab Reports, 1995\n•\t“Semiautomatic Camera Lens Calibration from Partially Known Structure”, Shawn Becker, MIT Media Lab Reports, 1994\n•\t[“Formulating a scene probability equation to differentiate the effects of shape & albedo on image brightness.”] Shawn Becker, MIT Media Lab Reports, 1994\n•\t“Computation of some projective-chirplet-transform & metaplectic-chirplet-transform subspaces, with applications in image processing.” Steve Mann & Shawn Becker, DSP World Symposium, Boston, Massachusetts, November 1992.\n• [C programming language], [TclTk], [X11], [HTML], [JavaScript],[CSS],[XMotif], [Bash], [Linux]"
  },
  {
    "role": "MS Computer Science",
    "employer": "BYU",
    "start": "Mon Aug 31 1987 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Fri Aug 31 1990 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "2",
    "css name": "mediumblue",
    "css RGB": "#0000cd",
    "text color": "#FFFFFF",
    "Description": "• Masters of Science degree, [BYU]{/static_content/portfolio/BYU-entrance-150x150.jpg}, Provo, Utah\nTook all courses required for both bachelors and masters degrees in Computer Science\n• Thesis project [“Interactive Measurement of Three-Dimensional Objects Using a Depth Buffer & Linear Probe.”] CS MS Thesis, Shawn Becker, William A. Barrett & Dan R. Olsen, ACM Transactions on Graphics, Vol. 10, No. 2, April 1991\n• Top Research Presentation – New Tech Research Conference - BYU – Provo, UT – March 1990\n• [“Fast Automated Object Detection Using Signature Parsing.”](http://www.spiedigitallibrary.org/conference-proceedings-of-spie/1192/1/Fast-Automated-Object-Detection-Using-Signature-Parsing/10.1117/12.969720.short) Tim Heaton; Shawn Becker; Kelley Anderson; William Barrett: Proceedings Volume 1192, Intelligent Robots & Computer Vision VIII: Algorithms & Techniques; (http://1990.com) https://doi.org/10.1117/12.969720\n• [“Probabilistic Segmentation of Myocardial Tissue by Deterministic Relaxation.”] Jerome A. Broekhuijsen, Shawn C. Becker, & William A. Barrett: IEEE Proceedings of Computers in Cardiology, pp. 99-12, Jerusalem, September 1989.\n• [“Interactive Measurement of three-Dimensional Cardiac Morphology.”]{/static_content/portfolio/BYU-MS-CS-Skull-Cross-Section-1.jpeg} Shawn C Becker, William A Barrett, October 1989, DOI: 10.1109/CIC.1989.130586, Conference: Computers in Cardiology.\n• [C programming language], [Bash], [Linux], [XMotif], and [X11]."
  },
  {
    "role": "Full Stack Developer",
    "employer": "Cimmetrix LLC",
    "start": "Tue May 31 1988 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "end": "Thu Aug 31 1989 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "3",
    "css name": "blueviolet",
    "css RGB": "#8a2be2",
    "text color": "#FFFFFF",
    "Description": "• Front-end software developer of a reverse kinametics path planning system for multi-axis industrial robots for [Cimmetrix]{/static_content/portfolio/Cimetrix-PDF-combined-logo-150x100.png}.\n• Technologies used include [Bash], [Linux], [C programming language], [Bash](http://en.wikipedia.org/wiki/Bourne_shell), [X11] , [Xt toolkit intrinsics](http://en.wikipedia.org/wiki/X_Toolkit_Intrinsics), [Silicon Graphics Irix](http://en.wikipedia.org/wiki/Silicon_Graphics), and [HP-UX](http://en.wikipedia.org/wiki/HP-UX)."
  },
  {
    "role": "Project Manager / Technical Lead ",
    "employer": "MSC ",
    "start": "Fri Nov 30 2007 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Sat Jul 31 2010 18:00:00 GMT-0600 (Mountain Daylight Time)",
    "z-index": "2",
    "css name": "yellow",
    "css RGB": "#ffff00",
    "text color": "#000000",
    "Description": "• MSC, now called [OneCall](http://onecallcm.com), is a leading workers compensation services company. \n• As project manager and technical lead for this Sierra Vista Group project, I presented fixed schedule-fixed budget project proposals to C-level executives to add features to their legacy call center system used by 10 different healthcare divisions. \n• Interviewed stakeholders to create functional requirements and technical spefications for each stage of development.\n• Worked with development team to create work plan, assign tasks.\n• Oversaw quality assurance and customer approval testing.\n• Used the MS Office suite of business apps a well as MS Visio. "
  },
  {
    "role": "Senior Architect ",
    "employer": "Eleven LLC",
    "start": "Tue Jan 31 2006 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Fri Nov 30 2007 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "2",
    "css name": "lime",
    "css RGB": "#00ff00",
    "text color": "#000000",
    "Description": "• [Eleven LLC](http://www.eleven.net) built mobile apps used by beverage industry distributors to help manage placement  of their products in the shelves and coolers in Resume locations. The work done by the Sierra Vista Group was instrumental in their company being acquired by [Trimble](http://help.trimblegeospatial.com/TMM/Home.htm). \n• As the architect and team lead, we used [Java], [Bash], [GitHub], [Linux], and  [JBoss](http://developers.redhat.com/products/eap/overview) message-oriented middleware platform, [Sybase Anywhere] for the client/server based database, and [Windows Mobile](http://en.wikipedia.org/wiki/Windows_Mobile_5.0) running on ruggedized mobile devices. "
  },
  {
    "role": "Senior Architect",
    "employer": "Intrusic LLC",
    "start": "Mon Jan 31 2005 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Tue Jan 31 2006 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "2",
    "css name": "limegreen",
    "css RGB": "#32cd32",
    "text color": "#000000",
    "Description": "• [Intrusic LLC] built real-time network monitoring systems that identified external and internal network intrusion attempts\n• As a Sierra Vista Group architech, I helped design and develop an approach for buffering live streaming network traffic for asynchronous package processing. \n• Used [Linux](http://www.debian.org), [C programming language](www.cprogramming.com/books/ritchie.html), and [Visio](http://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software)."
  },
  {
    "role": "Project Manager / Technical Lead ",
    "employer": "AMI Entertainment ",
    "start": "Sat Jan 31 2004 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Mon Jan 31 2005 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "2",
    "css name": "olivedrab",
    "css RGB": "#6b8e23",
    "text color": "#000000",
    "Description": "•  AMI (http://amientertainment.com) was the internet-music distribution incarnation of Rowe International.  \n•  As a Sierra Vista Group project manager and technical lead, I helped design and implement their system for making monthly ACH royalty payments to music copyright owners for mechanical and performance licensing rights.\n•  Used [FileMaker Pro](http://www.claris.com/filemaker/), [Bash], [Linux], [HTML], [CSS], [JavaScript], [Java], and [Visio](http://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software)."
  },
  {
    "role": "Project Manager / Technical Lead ",
    "employer": "Rowe International",
    "start": "Fri Feb 28 2003 17:00:00 GMT-0700 (Mountain Standard Time)",
    "end": "Sat Jan 31 2004 17:00:00 GMT-0700 (Mountain Standard Time)",
    "z-index": "2",
    "css name": "forestgreen",
    "css RGB": "#228b22",
    "text color": "#000000",
    "Description": "•  [Rowe International] was the leading manufacturer of music jukeboxes. \n•  Sierra Vista Group was consulted to assess their available technologies and create a plan to build their back-end systems to let them become a leading provider of internet-based music.\n•  As project manager and technical lead created the project plan and led the development of a full-stack web application used by  jukebox owners and Rowe sales and marketing.\n•  Used [Java], [Bash], [Linux], [HTML], [CSS], [JavaScript], [ObjectDesign](http://object.design/), [MySQL](http://www.mysql.com), and [Adobe Photoshop](http://www.adobe.com/products/photoshop.html). \n"
  }
];