const jobs = [
  {
    "role": "Senior Data Engineer ",
    "employer": "Spexture",
    "start": "2024-08-15",
    "end": "CURRENT_DATE",
    "z-index": "1",
    "Description": "• Implementing end-to-end MLOps CI/CD pipeline with target-based design\n• Hashicorp Terraform and Vault for multi-environment infrastructure and credentials\n• GitHub Actions for CI/CD and Argo CD for change detection\n• Kubernetes for orchestrating PySparkSQL Docker containers running on an EKS-managed cluster.\n• Amazon SageMaker for ML model integration, real-time scoring, and model versioning\n• Amazon Managed Grafana for real-time visualization\n• PySpark and PySpark SQL for data quality validation, data cleaning, and feature engineering \n• AWS Glue for metadata tagging, tracking versioning/lineage, and enforcing governance",
    "Skills": "Bash, CI/CD, DevOps, GitHub Actions, Hashicort Vault, Java, JavaScript/HTML/CSS, Node.js, Python, React, Schema Validation, Unit Testing",
    "references": [],
    "job-skills": {
      "44": "Bash",
      "49": "CI/CD",
      "70": "DevOps",
      "80": "GitHub Actions",
      "82": "Hashicort Vault",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "106": "Node.js",
      "118": "Python",
      "120": "React",
      "125": "Schema Validation",
      "153": "Unit Testing"
    }
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Fannie Mae / Risk & Corporate Systems",
    "start": "2024-02-17",
    "end": "2024-06-27",
    "z-index": "2",
    "Description": "• Extensive work with SQL, AWS Redshift, Glue, Airflow, S3, IAM, Lambda, REST, SNS, and dbt\n• Created dbt-validated SQL code for data cleansing and data lake ingestion \n• Used Amazon Glue to track schema changes and revise Redshift external views\n• Created custom views required for analysis and reporting in Redshift\n• Documented processes to build, test, and deploy data pipeline components for in-house ETL framework",
    "Skills": "Apache Airflow, Application Migrations, Application Monitoring, AWS CloudWatch, AWS IAM, AWS Lambda, AWS Redshift, AWS S3 Standard, CI/CD, Daily Scrum, Data Catalog, Data Engineering, Databases, Date Partitioning, DevOps, Docker, Docker Compose, ETL, Git, GitHub, Jenkins, Jira, KPI, Linux, Microsoft Excel, Python, Scrum, SDLC, Sprint Planning, Sprint Retrospective, Sprint Review, Sprints, SQL, Unit Testing",
    "references": [],
    "job-skills": {
      "6": "Apache Airflow",
      "8": "Application Migrations",
      "9": "Application Monitoring",
      "15": "AWS CloudWatch",
      "28": "AWS IAM",
      "31": "AWS Lambda",
      "34": "AWS Redshift",
      "36": "AWS S3 Standard",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "58": "Data Catalog",
      "61": "Data Engineering",
      "66": "Databases",
      "67": "Date Partitioning",
      "70": "DevOps",
      "73": "Docker",
      "74": "Docker Compose",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "92": "KPI",
      "95": "Linux",
      "101": "Microsoft Excel",
      "118": "Python",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "141": "SQL",
      "153": "Unit Testing"
    }
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "The Cigna Group - Data CyberSecurity Division",
    "start": "2023-05-01",
    "end": "2023-12-17",
    "z-index": "3",
    "Description": "• As a senior data engineer in the data cyber security team of the [Cigna Group] created a [REST API] using [Postman], [Bash], [Linux], and [OpenAPI] for pulling credentials from [CyberArk] using [OpenSSL] with [mutual TLS SSL authentication] via [API Gateway]. \n•  Migrated a suite of legacy [ETL][data pipeline] [Python] elements running on the [Unity IoC platform] with [PostgreSQL] and [S3] to pull credentials from the [CyberArk] identity service at runtime rather than using [Fernet] encrypted local files. \n•  Upgraded [GitHub] apps to use [Jenkins] [CI/CD pipeline] for build, applying software and cyber-security code checks, and on-prem server installation.",
    "Skills": "Apache Airflow, Application Migrations, Application Monitoring, AWS CloudWatch, AWS Glue, AWS IAM, AWS KMS, AWS Lambda, AWS Redshift, AWS S3 Standard, AWS Secrets Manager, AWS Step Functions, Bash, CI/CD, Cyber Security, Daily Scrum, Data Engineering, Databases, DevOps, Docker, Docker Compose, ETL, Git, GitHub, Jenkins, Jira, KPI, Linux, Microsoft Excel, Python, REST APIs, Scrum, SDLC, Sprint Planning, Sprint Retrospective, Sprint Review, Sprints, SQL, Unit Testing",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.thecignagroup.com/\">[Cigna Group]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.cyberark.com/\">[CyberArk]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.solace.com/Security/Two-Way-SSL-Authentication.htm\">[mutual TLS SSL authentication]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://cryptography.io/en/latest/fernet/\">[Fernet]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.aws.amazon.com/apigateway/\">[Jenkins]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.thecignagroup.com\">http://www.thecignagroup.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.cyberark.com\">http://www.cyberark.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://docs.solace.com/Security/Two-Way-SSL-Authentication.htm\">http://docs.solace.com/Security/Two-Way-SSL-Authentication.htm</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://cryptography.io/en/latest/fernet/\">http://cryptography.io/en/latest/fernet/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://docs.aws.amazon.com/apigateway/\">http://docs.aws.amazon.com/apigateway/</a></div>"
    ],
    "job-skills": {
      "6": "Apache Airflow",
      "8": "Application Migrations",
      "9": "Application Monitoring",
      "15": "AWS CloudWatch",
      "27": "AWS Glue",
      "28": "AWS IAM",
      "30": "AWS KMS",
      "31": "AWS Lambda",
      "34": "AWS Redshift",
      "36": "AWS S3 Standard",
      "38": "AWS Secrets Manager",
      "42": "AWS Step Functions",
      "44": "Bash",
      "49": "CI/CD",
      "54": "Cyber Security",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "73": "Docker",
      "74": "Docker Compose",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "92": "KPI",
      "95": "Linux",
      "101": "Microsoft Excel",
      "118": "Python",
      "122": "REST APIs",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "141": "SQL",
      "153": "Unit Testing"
    }
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Warner Bros. Interactive Entertainment",
    "start": "2022-09-01",
    "end": "2023-05-01",
    "z-index": "2",
    "Description": "• As a senior data engineer in the analytics team of [Warner Brothers] Division, implemented high-volume [ETL] [data pipeline] [integrations] transforming and sharing  game telemetry and [user PII data] between WB-distributed consumer games and [marketing service platforms] via [Segment customer data platform] using [Kafka], [Amazon S3], [Redshift], and [Apache Airflow]. \n• Employed [Python], [GitHub], [Bash], [Linux], [Amazon Glue] and [Apache Airflow] for external [3rd-party integrations] and internal dev-ops integrations with [Jenkins], [PostgreSQL], [DataDog],  [ZenDesk]. and [Tableau].\n• Integrated with [Google BigQuery](https://cloud.google.com/bigquery using  [Apache Airflow], [Amazon S3], and [Redshift].",
    "Skills": "Apache Airflow, Apache Kafka, Application Migrations, Application Monitoring, AWS CloudWatch, AWS IAM, AWS Lambda, AWS Redshift, AWS S3 Standard, AWS Step Functions, Bash, CI/CD, Daily Scrum, Data Dog, Data Engineering, Databases, DevOps, ETL, Git, GitHub, Google BigQuery, Infrastructure Monitoring, Jenkins, Jira, KPI, Linux, Martech, Microsoft Excel, New Relic, Python, Scrum, SDLC, Sprint Planning, Sprint Retrospective, Sprint Review, Sprints, SQL, Statistical Data Analysis, Unit Testing",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://warnerbrosgames.com/\">[Warner Brothers]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://segment.com/customer-data-platform/\">[Segment customer data platform]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/msk/\">[Kafka]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/redshift/\">[Redshift]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://airflow.apache.org\">[Apache Airflow]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/glue/\">[Amazon Glue]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://airflow.apache.org/\">[Apache Airflow]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.datadoghq.com/\">[DataDog]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://zendesk.com\">[ZenDesk]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/managed-workflows-for-apache-airflow/\">[Apache Airflow]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/redshift/\">[Redshift]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://warnerbrosgames.com\">http://warnerbrosgames.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://segment.com/customer-data-platform/\">http://segment.com/customer-data-platform/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/msk/\">http://aws.amazon.com/msk/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/redshift/\">http://aws.amazon.com/redshift/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://airflow.apache.org\">http://airflow.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/glue/\">http://aws.amazon.com/glue/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://airflow.apache.org\">http://airflow.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.datadoghq.com\">http://www.datadoghq.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://zendesk.com\">http://zendesk.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/managed-workflows-for-apache-airflow/\">http://aws.amazon.com/managed-workflows-for-apache-airflow/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/redshift/\">http://aws.amazon.com/redshift/</a></div>"
    ],
    "job-skills": {
      "6": "Apache Airflow",
      "7": "Apache Kafka",
      "8": "Application Migrations",
      "9": "Application Monitoring",
      "15": "AWS CloudWatch",
      "28": "AWS IAM",
      "31": "AWS Lambda",
      "34": "AWS Redshift",
      "36": "AWS S3 Standard",
      "42": "AWS Step Functions",
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "60": "Data Dog",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "81": "Google BigQuery",
      "83": "Infrastructure Monitoring",
      "87": "Jenkins",
      "88": "Jira",
      "92": "KPI",
      "95": "Linux",
      "97": "Martech",
      "101": "Microsoft Excel",
      "103": "New Relic",
      "118": "Python",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "141": "SQL",
      "143": "Statistical Data Analysis",
      "153": "Unit Testing"
    }
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Angel Studios ",
    "start": "2021-11-01",
    "end": "2022-09-01",
    "z-index": "1",
    "Description": "• Senior data engineer for [Angel Studios], a streaming media service that offers family-friendly entertainment that amplifies light, with titles including The Chosen, Dry Bar Comedy, and Tuttle Twins.\n• Used [Python], [GitHub], [Pandas], [Numpy], [Keras], [Bash], [Linux], [PostgreSQL], and [Jupyter] to build and tune hyperparameters of a [convolutional neural network] with [supervised learning] on [Amazon Sagemaker] to classify movie frames from episodic programs stored in [Amazon S3]. \n• Built web client apps using [Python] with [Postman] that made [REST] requests to pull monthly usage data from various web marketing partners like [FaceBook Marketing], [Google Play] , and [Vimeo]. \n• Worked with [Segment customer data platform], [Excel], and [Tableau] to create scheduled reports for the company's sales and finance teams.",
    "Skills": "Ansible, Applied Machine Learning, AWS SageMaker, Bash, CI/CD, CNN, Daily Scrum, Data Engineering, Databases, DevOps, ETL, Git, GitHub, Jenkins, Jira, Jupyter, Keras, KPI, Linux, Machine Learning, MatPlotLib, Microsoft Excel, numpy, Pandas, Python, PyTorch, Regularization, Scrum, SDLC, Statistical Data Analysis, Supervised Classification, Supervised Regression, Tableau, Unit Testing",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.angel.com/home\">[Angel Studios]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://jupyter.org/\">[Jupyter]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://towardsdatascience.com/a-comprehensive-guide-to-convolutional-neural-networks-the-eli5-way-3bd2b1164a53\">[convolutional neural network]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/pm/sagemaker/\">[Amazon Sagemaker]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/s3/storage-classes\">[Amazon S3]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.postman.com/\">[Postman]</a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[FaceBook Marketing]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://play.google/howplayworks/\">[Google Play]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://vimeo.com/\">[Vimeo]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://segment.com/customer-data-platform/\">[Segment customer data platform]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.angel.com/home\">http://www.angel.com/home</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://jupyter.org\">http://jupyter.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://towardsdatascience.com/a-comprehensive-guide-to-convolutional-neural-networks-the-eli5-way-3bd2b1164a53\">http://towardsdatascience.com/a-comprehensive-guide-to-convolutional-neural-networks-the-eli5-way-3bd2b1164a53</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/pm/sagemaker/\">http://aws.amazon.com/pm/sagemaker/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/s3/storage-classes\">http://aws.amazon.com/s3/storage-classes</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.postman.com\">http://www.postman.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://play.google/howplayworks/\">http://play.google/howplayworks/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://vimeo.com\">http://vimeo.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://segment.com/customer-data-platform/\">http://segment.com/customer-data-platform/</a></div>"
    ],
    "job-skills": {
      "5": "Ansible",
      "10": "Applied Machine Learning",
      "37": "AWS SageMaker",
      "44": "Bash",
      "49": "CI/CD",
      "50": "CNN",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "89": "Jupyter",
      "91": "Keras",
      "92": "KPI",
      "95": "Linux",
      "96": "Machine Learning",
      "98": "MatPlotLib",
      "101": "Microsoft Excel",
      "107": "numpy",
      "110": "Pandas",
      "118": "Python",
      "119": "PyTorch",
      "121": "Regularization",
      "128": "Scrum",
      "129": "SDLC",
      "143": "Statistical Data Analysis",
      "145": "Supervised Classification",
      "146": "Supervised Regression",
      "147": "Tableau",
      "153": "Unit Testing"
    }
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Data Laboratory / Greenseed",
    "start": "2020-11-01",
    "end": "2021-11-01",
    "z-index": "2",
    "Description": "• As a senior software engineer for Data Laboratory, an internet company that provides daily lead reports for independent real-estage agents world-wide, I  [containerized] legacy web applications using [Bash], [Linux], [GitHub], [Docker] and [Amazon Secrets Manager]. \n• Updated legacy web apps using [Bash], [Linux], [HTML], [CSS], [JavaScript], [PostgreSQL], [NGINX], and [OpenSSL].\n• Documented existing data architecture as [ERDs] using [DBeaver Enterprise].",
    "Skills": "AWS CloudFormation, AWS CloudWatch, AWS EC2, AWS ECR, AWS ECS, AWS EFS, AWS EKS, AWS Fargate, AWS IAM, AWS Lambda, AWS S3 Standard, Bash, CI/CD, Daily Scrum, Data Cleansing, Data Engineering, Databases, DevOps, Docker, Docker Compose, ETL, Git, GitHub, Jenkins, Jira, KPI, Kubernetes, Linux, Mentoring, Microsoft Excel, PostgreSQL, Python, REST APIs, Scrum, SDLC, SQL, Tech Project Manager, Terraform, Unit Testing",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.docker.com/\">[Docker]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/secrets-manager/\">[Amazon Secrets Manager]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.lucidchart.com/pages/er-diagrams\">[ERDs]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://dbeaver.com/dbeaver-enterprise/\">[DBeaver Enterprise]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.docker.com\">http://www.docker.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/secrets-manager/\">http://aws.amazon.com/secrets-manager/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.lucidchart.com/pages/er-diagrams\">http://www.lucidchart.com/pages/er-diagrams</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://dbeaver.com/dbeaver-enterprise/\">http://dbeaver.com/dbeaver-enterprise/</a></div>"
    ],
    "job-skills": {
      "13": "AWS CloudFormation",
      "15": "AWS CloudWatch",
      "19": "AWS EC2",
      "20": "AWS ECR",
      "21": "AWS ECS",
      "22": "AWS EFS",
      "23": "AWS EKS",
      "26": "AWS Fargate",
      "28": "AWS IAM",
      "31": "AWS Lambda",
      "36": "AWS S3 Standard",
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "59": "Data Cleansing",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "73": "Docker",
      "74": "Docker Compose",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "92": "KPI",
      "93": "Kubernetes",
      "95": "Linux",
      "100": "Mentoring",
      "101": "Microsoft Excel",
      "114": "PostgreSQL",
      "118": "Python",
      "122": "REST APIs",
      "128": "Scrum",
      "129": "SDLC",
      "141": "SQL",
      "149": "Tech Project Manager",
      "150": "Terraform",
      "153": "Unit Testing"
    }
  },
  {
    "role": "Senior Full-Stack Developer ",
    "employer": "NuSkin",
    "start": "2019-11-01",
    "end": "2020-11-01",
    "z-index": "1",
    "Description": "• As a senior full stack developer for [NuSkin](https://www.nuskin.com/us/en/, an international company known for its excellent  skin and beauty products I created new [Vue.js], [Nuxt], and [Vuetify] components using [Bash], [Linux], [GitHub], [NodeJS], [HTML] and [CSS].  \n• Internationalized content using [Adobe Experience Cloud].",
    "Skills": "Bash, CI/CD, Daily Scrum, Data Engineering, Databases, DevOps, Front-End, Git, GitHub, Jenkins, Jira, Linux, Microsoft Excel, Node.js, Plotly, SaaS, Scrum, SDLC, Sprint Planning, Sprint Retrospective, Sprint Review, Sprints, Unit Testing, Vue.js",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://vuejs.org/\">[Vue.js]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://nuxt.com/\">[Nuxt]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://vuetifyjs.com/en/\">[Vuetify]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://business.adobe.com/\">[Adobe Experience Cloud]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://vuejs.org\">http://vuejs.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://nuxt.com\">http://nuxt.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://vuetifyjs.com/en/\">http://vuetifyjs.com/en/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"business.adobe.com/\">business.adobe.com/</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "95": "Linux",
      "101": "Microsoft Excel",
      "106": "Node.js",
      "113": "Plotly",
      "123": "SaaS",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "153": "Unit Testing",
      "155": "Vue.js"
    }
  },
  {
    "role": "Senior Data Engineer ",
    "employer": "Seniorlink / Vela",
    "start": "2017-03-01",
    "end": "2019-11-01",
    "z-index": "2",
    "Description": "• As a senior data engineer for SeniorLink's [Vela project]{/static_content/portfolio/Vela-150x126.png} a homeservices support platform, helped create [ETL] processes using [Amazon Kinesis], [Python], [PySpark], and [Amazon Data Pipeline] to load structured event data from [PostgreSQL] databases into [Redshift]. \n• Saved data to [Amazon S3] using [Amazon Kinesis] and triggered [Amazon Lambda] jobs to aggregate steaming event data into [schema-on-read] file formats, [Apache Avro] and [Apache Parquet].\n• Steered efforts in creating a [Data Lake] using [PostgreSQL] and [FlyWay] with [Python] and [PySpark] pre-processing on [EC2 instances] using shared [Amazon EFS] for staged storage.\n• Used streaming event messages queued in [RabbitMQ] and [Amazon Kinesis] to build [type-2 slowly changing dimensions] and accumulative facts tables. \n• Designed and implemented a custom [star-schema warehouse] and [ETL] processes to [de-normalize] and load data into [Redshift] data warehouse for BI reporting using [Tableau].\n• [Test-driven development] using [Bash], [Linux], [Python], [PyCharm], [PyTest], [Unit-test], [GitHub], [Jira], and [Jenkins].",
    "Skills": "Application Monitoring, AWS CloudWatch, AWS DataPipeline, AWS EBS, AWS EC2, AWS ECS, AWS EFS, AWS EMR, AWS IAM, AWS Kinesis, AWS Lambda, AWS RDS, AWS Redshift, AWS S3 Standard, AWS SNS, AWS SQS, Bash, CI/CD, Daily Scrum, Data Architecture, Data Engineering, Data Modeling, Database Design, Databases, Date Partitioning, Denormalization, DevOps, Dimensional Modeling, ETL, Git, GitHub, Java, Jenkins, Jira, Linux, Microsoft Excel, PostgreSQL, PySpark EMR, Python, REST APIs, Schema Evolution, Schema Validation, Scrum, SDLC, Sprint Planning, Sprint Retrospective, Sprint Review, Sprints, Strategic Planning, Tableau, Unit Testing, Visio",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/what-is/etl/\">[ETL]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/pm/kinesis/\">[Amazon Kinesis]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://spark.apache.org/\">[PySpark]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/what-is-datapipeline.html\">[Amazon Data Pipeline]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/pm/redshift/\">[Redshift]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.aws.amazon.com/lambda/\">[Amazon Lambda]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://avro.apache.org/\">[Apache Avro]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://parquet.apache.org/\">[Apache Parquet]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/big-data/datalakes-and-analytics/datalakes/\">[Data Lake]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://flywaydb.org/\">[FlyWay]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://spark.apache.org/docs/latest/api/python/index.html\">[PySpark]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://zesty.co/blog/ebs-vs-efs-which-is-right\">[Amazon EFS]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/working-with-rabbitmq.html\">[RabbitMQ]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.databricks.com/glossary/star-schema\">[star-schema warehouse]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/Denormalization\">[de-normalize]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/redshift/\">[Redshift]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.tableau.com/\">[Tableau]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.pluralsight.com/blog/software-development/tdd-vs-bdd\">[Test-driven development]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.jenkins.io/\">[Jenkins]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/what-is/etl/\">http://aws.amazon.com/what-is/etl/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/pm/kinesis/\">http://aws.amazon.com/pm/kinesis/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://spark.apache.org\">http://spark.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/what-is-datapipeline.html\">http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/what-is-datapipeline.html</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/pm/redshift/\">http://aws.amazon.com/pm/redshift/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://docs.aws.amazon.com/lambda/\">http://docs.aws.amazon.com/lambda/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://avro.apache.org\">http://avro.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://parquet.apache.org\">http://parquet.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/big-data/datalakes-and-analytics/datalakes/\">http://aws.amazon.com/big-data/datalakes-and-analytics/datalakes/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://flywaydb.org\">http://flywaydb.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://spark.apache.org/docs/latest/api/python/index.html\">http://spark.apache.org/docs/latest/api/python/index.html</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://zesty.co/blog/ebs-vs-efs-which-is-right\">http://zesty.co/blog/ebs-vs-efs-which-is-right</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://docs.aws.amazon.com/amazon-mq/latest/developer-guide/working-with-rabbitmq.html\">http://docs.aws.amazon.com/amazon-mq/latest/developer-guide/working-with-rabbitmq.html</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.databricks.com/glossary/star-schema\">http://www.databricks.com/glossary/star-schema</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://en.wikipedia.org/wiki/Denormalization\">http://en.wikipedia.org/wiki/Denormalization</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/redshift/\">http://aws.amazon.com/redshift/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.tableau.com\">http://www.tableau.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.pluralsight.com/blog/software-development/tdd-vs-bdd\">http://www.pluralsight.com/blog/software-development/tdd-vs-bdd</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.jenkins.io/\">http://www.jenkins.io/</a></div>"
    ],
    "job-skills": {
      "9": "Application Monitoring",
      "15": "AWS CloudWatch",
      "16": "AWS DataPipeline",
      "18": "AWS EBS",
      "19": "AWS EC2",
      "21": "AWS ECS",
      "22": "AWS EFS",
      "25": "AWS EMR",
      "28": "AWS IAM",
      "29": "AWS Kinesis",
      "31": "AWS Lambda",
      "33": "AWS RDS",
      "34": "AWS Redshift",
      "36": "AWS S3 Standard",
      "40": "AWS SNS",
      "41": "AWS SQS",
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "56": "Data Architecture",
      "61": "Data Engineering",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "67": "Date Partitioning",
      "69": "Denormalization",
      "70": "DevOps",
      "71": "Dimensional Modeling",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "87": "Jenkins",
      "88": "Jira",
      "95": "Linux",
      "101": "Microsoft Excel",
      "114": "PostgreSQL",
      "117": "PySpark EMR",
      "118": "Python",
      "122": "REST APIs",
      "124": "Schema Evolution",
      "125": "Schema Validation",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "144": "Strategic Planning",
      "147": "Tableau",
      "153": "Unit Testing",
      "154": "Visio"
    }
  },
  {
    "role": "Senior Back-End Engineer ",
    "employer": "BigR.io",
    "start": "2016-12-01",
    "end": "2017-03-01",
    "z-index": "1",
    "Description": "• As a senior software engineer at [BigR.io]{/static_content/portfolio/Bigr.io_-150x106.png} I used [Amazon microservices] for custom voice-based [natural language processing] applications.\n• Used [Apache ActiveMQ], [Swagger], [JSON], [Jackson], [AOP], [Eclipse], [Maven], [GitHub], [Jira], [PostgreSQL], and [Jenkins].\n• [Java], [J2EE], [Servlets], [Spring], [SpringBoot], [JAX-RS], [Bash], [Linux], [JUnit], [JMeter], and [JProfile]",
    "Skills": "Bash, CI/CD, Daily Scrum, Data Engineering, Databases, DevOps, Front-End, Git, GitHub, Jenkins, Jira, Linux, Microsoft Excel, Node.js, Plotly, SaaS, Scrum, SDLC, Sprint Planning, Sprint Retrospective, Sprint Review, Sprints, Unit Testing, Vue.js",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://activemq.apache.org/\">[Apache ActiveMQ]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://swagger.io/\">[Swagger]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://url.com\">[Jackson]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.baeldung.com/spring-aop\">[AOP]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://activemq.apache.org\">http://activemq.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://swagger.io/\">http://swagger.io/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://url.com\">http://url.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.baeldung.com/spring-aop\">http://www.baeldung.com/spring-aop</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "95": "Linux",
      "101": "Microsoft Excel",
      "106": "Node.js",
      "113": "Plotly",
      "123": "SaaS",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "153": "Unit Testing",
      "155": "Vue.js"
    }
  },
  {
    "role": "Technical Lead / Co-Founder ",
    "employer": "ClipFile LLC",
    "start": "2011-02-01",
    "end": "2016-12-01",
    "z-index": "2",
    "Description": "• Co-founded [ClipFile]{/static_content/portfolio/clipfile-infrastructure-150x150.png}, a company that envisioned building a web destination where users could easily record and share their favorite pieces of content like facts, authored stories, quotes, articles, chapters, or personal thoughts, as a way of concretely defining their personal [mindset]http://sourcesofinsight.com/what-is-mindset/.\n• Implemented [fuzzy matching], [word clustering], [semantic similarity scores], and [collaborative filtering] to help users find content that matched or differed from thieir own mindset.\n• Launched a novel [SaaS] using [Amazon Web Services] that let individuals and content creators search and share mindsets.\n• Conceptualized patented technology by designing and implementing a fuil-stack consumer-facing content management system that supported tuned matching among selected attributes.\n• [Java], [J2EE], [JSP], [Servlets], [Spring], [Amazon services], [JavaScript], [JQuery], [HTML], [CSS], [JUnit], [JMeter], [JProfile].\n• Utilized [REST], [Swagger], [Apache Shiro], [Eclipse IDE], [Apache Maven], [Apache Ant], [GitHub], [Hibernate], [Amazon SimpleDB], [Linux], [Apache Tomcat], [Bash], [Linux], [Jetty], and [Spring MVC].\n• Served as co-founder and co-authored [four patents].",
    "Skills": "AWS CloudWatch, AWS DynamoDB, AWS EC2, AWS EFS, AWS Elastic Beanstalk, AWS IAM, AWS Lambda, AWS Load Balancer, AWS Route 53, AWS S3 Standard, AWS SimpleDB, AWS SNS, AWS SQS, AWS VPC, Bash, Bayesian Clustering, Collaborative Filtering, Data Architecture, Data Modeling, Database Design, Databases, DevOps, Dimensionality Reduction, Front-End, Full-Stack, Git, GitHub, JavaScript/HTML/CSS, K-means clustering, Linux, Machine Learning, Mentoring, Microsoft Excel, nltk, Pattern Recognition, REST APIs, SaaS, SDLC, Sentiment Analysis, Spring, Spring Boot, Spring MVC, Sprint Planning, SQL, Strategic Planning, Tech Product Manager, Visio",
    "references": [
      "<div class=\"img-ref\">[mindset]<img src=\"https://sourcesofinsight.com/wp-content/uploads/2014/04/Mindset-768x505.jpg\"/></div>",
      "<div class=\"img-ref anchor-ref\">[mindset]<a href=\"https://sourcesofinsight.com/what-is-mindset/\"><img src=\"https://sourcesofinsight.com/wp-content/uploads/2014/04/Mindset-768x505.jpg\"/></a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://nanonets.com/blog/fuzzy-matching-fuzzy-logic/\">[fuzzy matching]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.ilc.cnr.it/EAGLES96/rep2/node37.html#:~:text=Word%20clustering%20is%20a%20technique,to%20information%20retrieval%20and%20filtering.\">[word clustering]</a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[semantic similarity scores]</a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[collaborative filtering]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://shiro.apache.org/\">[Apache Shiro]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.eclipse.org/home/whatis/\">[Eclipse IDE]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://maven.apache.org/what-is-maven.html\">[Apache Maven]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://ant.apache.org/\">[Apache Ant]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/simpledb/\">[Amazon SimpleDB]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.centos.org/\">[Linux]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://tomcat.apache.org/\">[Apache Tomcat]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://projects.eclipse.org/projects/rt.jetty\">[Jetty]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.spring.io/spring-framework/reference/web/webmvc.html\">[Spring MVC]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.freepatentsonline.com/y2013/0325870.html\">[four patents]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://sourcesofinsight.com/what-is-mindset/\">http://sourcesofinsight.com/what-is-mindset/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://nanonets.com/blog/fuzzy-matching-fuzzy-logic/\">http://nanonets.com/blog/fuzzy-matching-fuzzy-logic/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.ilc.cnr.it/EAGLES96/rep2/node37.html#:~:text=Word%20clustering%20is%20a%20technique,to%20information%20retrieval%20and%20filtering.\">http://www.ilc.cnr.it/EAGLES96/rep2/node37.html#:~:text=Word%20clustering%20is%20a%20technique,to%20information%20retrieval%20and%20filtering.</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://shiro.apache.org\">http://shiro.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.eclipse.org/home/whatis/\">http://www.eclipse.org/home/whatis/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://maven.apache.org/what-is-maven.html\">http://maven.apache.org/what-is-maven.html</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://ant.apache.org\">http://ant.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://aws.amazon.com/simpledb/\">http://aws.amazon.com/simpledb/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.centos.org\">http://www.centos.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://tomcat.apache.org\">http://tomcat.apache.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://projects.eclipse.org/projects/rt.jetty\">http://projects.eclipse.org/projects/rt.jetty</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://docs.spring.io/spring-framework/reference/web/webmvc.html\">http://docs.spring.io/spring-framework/reference/web/webmvc.html</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.freepatentsonline.com/y2013/0325870.html\">http://www.freepatentsonline.com/y2013/0325870.html</a></div>"
    ],
    "job-skills": {
      "15": "AWS CloudWatch",
      "17": "AWS DynamoDB",
      "19": "AWS EC2",
      "22": "AWS EFS",
      "24": "AWS Elastic Beanstalk",
      "28": "AWS IAM",
      "31": "AWS Lambda",
      "32": "AWS Load Balancer",
      "35": "AWS Route 53",
      "36": "AWS S3 Standard",
      "39": "AWS SimpleDB",
      "40": "AWS SNS",
      "41": "AWS SQS",
      "43": "AWS VPC",
      "44": "Bash",
      "45": "Bayesian Clustering",
      "51": "Collaborative Filtering",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "72": "Dimensionality Reduction",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "86": "JavaScript/HTML/CSS",
      "90": "K-means clustering",
      "95": "Linux",
      "96": "Machine Learning",
      "100": "Mentoring",
      "101": "Microsoft Excel",
      "105": "nltk",
      "111": "Pattern Recognition",
      "122": "REST APIs",
      "123": "SaaS",
      "129": "SDLC",
      "131": "Sentiment Analysis",
      "134": "Spring",
      "135": "Spring Boot",
      "136": "Spring MVC",
      "137": "Sprint Planning",
      "141": "SQL",
      "144": "Strategic Planning",
      "148": "Tech Product Manager",
      "154": "Visio"
    }
  },
  {
    "role": "Lead Solutions Architect / Co-Founder ",
    "employer": "Sierra Vista Group, LLC",
    "start": "2002-11-01",
    "end": "2011-02-01",
    "z-index": "1",
    "Description": "• Co-founded a finance and technology boutique called [Sierra Vista Group] that delivered support in planning and proposing effective IT strategies for key clients in several industries. \n• Performed various services, including system and architecture assessment and solutions design, to ensure the smooth running of technical projects.\n• Managed project schedules and technical specifications to match business requirements within contractual budget constraints. \n• Identified opportunities for potential clients requiring expertise in product development, software engineering, and data modeling. Negotiated and communicated with c-level client management regarding project milestone agreements.\n• Increased ROI for each client’s project by hiring and managing contractors to deliver custom software solutions.\n• Delivered high-level leadership and guidance to a team of software engineering consultants for several projects to accelerate operational excellence.",
    "Skills": "AWS CloudWatch, AWS IAM, Bash, Business Requirements, Data Architecture, Data Modeling, Database Design, Databases, DevOps, Front-End, Full-Stack, Git, GitHub, JavaScript/HTML/CSS, Leadership, Linux, Mentoring, Microsoft Excel, Microsoft Project, Presentation Skills, Project Risk, SaaS, SDLC, SQL, Stakeholder Management, Strategic Planning, Tech Product Manager, User Acceptance Testing, Visio",
    "references": [
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[Sierra Vista Group]</a></div>"
    ],
    "job-skills": {
      "15": "AWS CloudWatch",
      "28": "AWS IAM",
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "100": "Mentoring",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "123": "SaaS",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "148": "Tech Product Manager",
      "152": "User Acceptance Testing",
      "154": "Visio"
    }
  },
  {
    "role": "Technical Lead / Co-Founder ",
    "employer": "HomePortfolio, Inc.",
    "start": "1998-02-01",
    "end": "2002-11-01",
    "z-index": "1",
    "Description": "• As co-founder and CTO, designed and led the development of a public website used by discerning home designers and builders called [HomePortfolio]. \n• Hired a staff of  10 software and databases developers. \n• Worked with data acquisition team to scan and tag over 700,000 premium home design products from over 2,000 manufactures and vendors.\n• Designed datamodel and data entry tools for category-specific product attribution. \n• Helped extended the business model to provide online product selection tools for participating vendors and manufacturers.\n• Instrumental in raising over $70M in venture capital. \n• Used [Oracle], [ATG Dyanamo]( https://docs.oracle.com/cd/E24152_01/Platform.10-1/ATGPersBusinessGuide/html/s0102dynamoapplicationframework01.html), [Java], [Akamai]www.akamai.com/, [WebTrends], [FileMakerPro], [ImageMagik], [Bash], [Linux], [HTML], [JavaScript], [CSS], and [Omnigraffle] for data modeling and workflow designs.",
    "Skills": "Akamai, Algorithms, Application Monitoring, ATG Dynamo, AWS CloudWatch, AWS IAM, Bash, Data Architecture, Data Modeling, Database Design, Databases, DevOps, Front-End, Full-Stack, Git, GitHub, Java, JavaScript/HTML/CSS, Leadership, Linux, Microsoft Excel, Oracle Database, SDLC, SEO, SQL, Director",
    "references": [
      "<div class=\"img-ref\">[Akamai]<img src=\"https://www.hiclipart.com/free-transparent-background-png-clipart-zkmsn\"/></div>",
      "<div class=\"img-ref anchor-ref\">[Akamai]<a href=\"https://www.akamai.com/\"><img src=\"https://www.hiclipart.com/free-transparent-background-png-clipart-zkmsn\"/></a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[HomePortfolio]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.webtrends.com/\">[WebTrends]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://imagemagick.org/index.php\">[ImageMagik]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.omnigroup.com/omnigraffle\">[Omnigraffle]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"www.akamai.com/\">www.akamai.com/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.webtrends.com\">http://www.webtrends.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://imagemagick.org/index.php\">http://imagemagick.org/index.php</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.omnigroup.com/omnigraffle\">http://www.omnigroup.com/omnigraffle</a></div>"
    ],
    "job-skills": {
      "3": "Akamai",
      "4": "Algorithms",
      "9": "Application Monitoring",
      "11": "ATG Dynamo",
      "15": "AWS CloudWatch",
      "28": "AWS IAM",
      "44": "Bash",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "109": "Oracle Database",
      "129": "SDLC",
      "132": "SEO",
      "141": "SQL",
      "156": "Director"
    }
  },
  {
    "role": "Lead Software Developer ",
    "employer": "BuildingBlocks, LLC",
    "start": "1996-06-01",
    "end": "1998-02-01",
    "z-index": "1",
    "Description": "• As lead software developer, built a CD-ROM-based home design application for selecting premium home design products for previewing in the context of images of any household rooms. \n• Built the prototype using Adobe Photoshop and [Macromedia Director].\n• Built the actual application using using [Bash], [Linux], [Java] and [Marimba Bongo] widget layout tool.\n• Updates for the self-updating application were delivered over the internet using [Marimba Castanet] push-technology.",
    "Skills": "JavaScript/HTML/CSS, Director",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://macromedia.fandom.com/wiki/Macromedia_Director\">[Macromedia Director]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.thriftbooks.com/w/official-marimba-guide-to-bongo_danny-goodman/2574616/#edition=58026223&idiq=42367912\">[Marimba Bongo]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.infoworld.com/article/2076707/marimba-launches-new-castanet-with-a-less-java-centric-focus.html\">[Marimba Castanet]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://macromedia.fandom.com/wiki/Macromedia_Director\">http://macromedia.fandom.com/wiki/Macromedia_Director</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.thriftbooks.com/w/official-marimba-guide-to-bongo_danny-goodman/2574616/#edition=58026223&idiq=42367912\">http://www.thriftbooks.com/w/official-marimba-guide-to-bongo_danny-goodman/2574616/#edition=58026223&idiq=42367912</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.infoworld.com/article/2076707/marimba-launches-new-castanet-with-a-less-java-centric-focus.html\">http://www.infoworld.com/article/2076707/marimba-launches-new-castanet-with-a-less-java-centric-focus.html</a></div>"
    ],
    "job-skills": {
      "86": "JavaScript/HTML/CSS",
      "156": "Director"
    }
  },
  {
    "role": "Ph.D. Media Arts & Science",
    "employer": "MIT Media Lab",
    "start": "1990-09-01",
    "end": "1997-04-01",
    "z-index": "2",
    "Description": "•\tDoctor of Philosopy degree, [MIT]{/static_content/portfolio/MIT-logo.png}, Cambridge, Massachusettes\n•\tMedia Laboratory, Media Arts and Sciences\n•\tTook courses in machine vision, signals and systems, digital signal processing, and stochastics.\n•\tHelped build the operating system for the [Cheops multi-processor system] used for digital video research and for holographic video\n•\t[“Vision-assisted modeling for model-based video representations”], (Ph.D. Dissertation) MIT, Program in Media Arts & Sciences, 1997\n•\t[“Semiautomatic 3-D Model Extraction from Uncalibrated 2-D Camera Views.”] S. Becker & V. M. Bove, Jr., Proc. SPIE Image Synthesis, 2410, 1995, pp. 447-461.\n•\t“Semiautomatic Scene Modeling From 2-D Views with Partially Known Structure.” Shawn Becker, MIT Media Lab Reports, 1995\n•\t“Semiautomatic Camera Lens Calibration from Partially Known Structure”, Shawn Becker, MIT Media Lab Reports, 1994\n•\t[“Formulating a scene probability equation to differentiate the effects of shape & albedo on image brightness.”] Shawn Becker, MIT Media Lab Reports, 1994\n•\t“Computation of some projective-chirplet-transform & metaplectic-chirplet-transform subspaces, with applications in image processing.” Steve Mann & Shawn Becker, DSP World Symposium, Boston, Massachusetts, November 1992.\n• [C programming language], [TclTk], [X11], [HTML], [JavaScript],[CSS],[XMotif], [Bash], [Linux]",
    "Skills": "Algorithms, Applied Machine Learning, Bash, Bayesian Clustering, C, Computer Vision, Front-End, Full-Stack, JavaScript/HTML/CSS, Leadership, Linux, Machine Learning, Pattern Recognition, Project Risk, SDLC, Statistical Data Analysis, Supervised Regression, Visio",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"http://alumni.media.mit.edu/~wad/cheops_CSVT/cheops.html\">[Cheops multi-processor system]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://dspace.mit.edu/handle/1721.1/29123\">[“Vision-assisted modeling for model-based video representations”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.media.mit.edu/publications/semiautomatic-3-d-model-extraction-from-uncalibrated-2-d-camera-views-2/\">[“Semiautomatic 3-D Model Extraction from Uncalibrated 2-D Camera Views.”]</a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[“Formulating a scene probability equation to differentiate the effects of shape & albedo on image brightness.”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://alumni.media.mit.edu/~wad/cheops_CSVT/cheops.html\">http://alumni.media.mit.edu/~wad/cheops_CSVT/cheops.html</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://dspace.mit.edu/handle/1721.1/29123\">http://dspace.mit.edu/handle/1721.1/29123</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.media.mit.edu/publications/semiautomatic-3-d-model-extraction-from-uncalibrated-2-d-camera-views-2/\">http://www.media.mit.edu/publications/semiautomatic-3-d-model-extraction-from-uncalibrated-2-d-camera-views-2/</a></div>"
    ],
    "job-skills": {
      "4": "Algorithms",
      "10": "Applied Machine Learning",
      "44": "Bash",
      "45": "Bayesian Clustering",
      "47": "C",
      "52": "Computer Vision",
      "76": "Front-End",
      "77": "Full-Stack",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "96": "Machine Learning",
      "111": "Pattern Recognition",
      "116": "Project Risk",
      "129": "SDLC",
      "143": "Statistical Data Analysis",
      "146": "Supervised Regression",
      "154": "Visio"
    }
  },
  {
    "role": "MS Computer Science",
    "employer": "BYU",
    "start": "1987-09-01",
    "end": "1990-09-01",
    "z-index": "2",
    "Description": "• Masters of Science degree, [BYU]{/static_content/portfolio/BYU-entrance-150x150.jpg}, Provo, Utah\nTook all courses required for both bachelors and masters degrees in Computer Science\n• Thesis project [“Interactive Measurement of Three-Dimensional Objects Using a Depth Buffer & Linear Probe.”] CS MS Thesis, Shawn Becker, William A. Barrett & Dan R. Olsen, ACM Transactions on Graphics, Vol. 10, No. 2, April 1991\n• Top Research Presentation – New Tech Research Conference - BYU – Provo, UT – March 1990\n• [“Fast Automated Object Detection Using Signature Parsing.”] Tim Heaton; Shawn Becker; Kelley Anderson; William Barrett: Proceedings Volume 1192, Intelligent Robots & Computer Vision VIII: Algorithms & Techniques; http://1990.com https://doi.org/10.1117/12.969720\n• [“Probabilistic Segmentation of Myocardial Tissue by Deterministic Relaxation.”] Jerome A. Broekhuijsen, Shawn C. Becker, & William A. Barrett: IEEE Proceedings of Computers in Cardiology, pp. 99-12, Jerusalem, September 1989.\n• [“Interactive Measurement of three-Dimensional Cardiac Morphology.”] Shawn C Becker, William A Barrett, October 1989, DOI: 10.1109/CIC.1989.130586, Conference: Computers in Cardiology.\n• [C programming language], [Bash], [Linux], [XMotif], and [X11].",
    "Skills": "Bash, CI/CD, Daily Scrum, Data Engineering, Databases, DevOps, Front-End, Git, GitHub, Jenkins, Jira, Linux, Microsoft Excel, Node.js, Plotly, SaaS, Scrum, SDLC, Sprint Planning, Sprint Retrospective, Sprint Review, Sprints, Unit Testing, Vue.js",
    "references": [
      "<div class=\"img-ref-not-found anchor-ref-not-found\">[“Interactive Measurement of three-Dimensional Cardiac Morphology.”]<a href=\"\"><img src=\"/static_content/portfolio/BYU-MS-CS-Skull-Cross-Section-1.jpeg\"/></a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[“Interactive Measurement of Three-Dimensional Objects Using a Depth Buffer & Linear Probe.”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.spiedigitallibrary.org/conference-proceedings-of-spie/1192/1/Fast-Automated-Object-Detection-Using-Signature-Parsing/10.1117/12.969720.short\">[“Fast Automated Object Detection Using Signature Parsing.”]</a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[“Probabilistic Segmentation of Myocardial Tissue by Deterministic Relaxation.”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.spiedigitallibrary.org/conference-proceedings-of-spie/1192/1/Fast-Automated-Object-Detection-Using-Signature-Parsing/10.1117/12.969720.short\">http://www.spiedigitallibrary.org/conference-proceedings-of-spie/1192/1/Fast-Automated-Object-Detection-Using-Signature-Parsing/10.1117/12.969720.short</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://1990.com\">http://1990.com</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "95": "Linux",
      "101": "Microsoft Excel",
      "106": "Node.js",
      "113": "Plotly",
      "123": "SaaS",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "153": "Unit Testing",
      "155": "Vue.js"
    }
  },
  {
    "role": "Full Stack Developer",
    "employer": "Cimetrix Incorporated",
    "start": "1988-06-01",
    "end": "1989-09-01",
    "z-index": "3",
    "Description": "• Front-end software developer of a reverse kinametics path planning system for multi-axis industrial robots for [Cimmetrix]{/static_content/portfolio/Cimetrix-PDF-combined-logo-150x100.png}.\n• Technologies used include [Bash], [Linux], [C programming language], [Bash], [X11] , [Xt toolkit intrinsics], [Silicon Graphics Irix], and [HP-UX].",
    "Skills": "Bash, C, Front-End, Full-Stack, JavaScript/HTML/CSS, Linux, SDLC",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/Bourne_shell\">[Bash]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/X_Toolkit_Intrinsics\">[Xt toolkit intrinsics]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/Silicon_Graphics\">[Silicon Graphics Irix]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/HP-UX\">[HP-UX]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://en.wikipedia.org/wiki/Bourne_shell\">http://en.wikipedia.org/wiki/Bourne_shell</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://en.wikipedia.org/wiki/X_Toolkit_Intrinsics\">http://en.wikipedia.org/wiki/X_Toolkit_Intrinsics</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://en.wikipedia.org/wiki/Silicon_Graphics\">http://en.wikipedia.org/wiki/Silicon_Graphics</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://en.wikipedia.org/wiki/HP-UX\">http://en.wikipedia.org/wiki/HP-UX</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "47": "C",
      "76": "Front-End",
      "77": "Full-Stack",
      "86": "JavaScript/HTML/CSS",
      "95": "Linux",
      "129": "SDLC"
    }
  },
  {
    "role": "Project Manager / Technical Lead ",
    "employer": "One Call Care Management (formerly MSC Care Management)",
    "start": "2007-12-01",
    "end": "2010-08-01",
    "z-index": "2",
    "Description": "• MSC, now called [OneCall], is a leading workers compensation services company. \n• As project manager and technical lead for this Sierra Vista Group project, I presented fixed schedule-fixed budget project proposals to C-level executives to add features to their legacy call center system used by 10 different healthcare divisions. \n• Interviewed stakeholders to create functional requirements and technical spefications for each stage of development.\n• Worked with development team to create work plan, assign tasks.\n• Oversaw quality assurance and customer approval testing.\n• Used the MS Office suite of business apps a well as MS Visio.",
    "Skills": "Bash, Business Requirements, Data Architecture, Data Modeling, Database Design, Databases, DevOps, Git, GitHub, Leadership, Linux, Microsoft Excel, Microsoft Project, Presentation Skills, Project Risk, SDLC, SQL, Stakeholder Management, Strategic Planning, Tech Project Manager, User Acceptance Testing",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://onecallcm.com/\">[OneCall]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://onecallcm.com\">http://onecallcm.com</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "78": "Git",
      "79": "GitHub",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "role": "Senior Architect ",
    "employer": "11Mobile / Trimble Inc.",
    "start": "2006-02-01",
    "end": "2007-12-01",
    "z-index": "2",
    "Description": "• [Eleven LLC] built mobile apps used by beverage industry distributors to help manage placement  of their products in the shelves and coolers in retail locations. The work done by the Sierra Vista Group was instrumental in their company being acquired by [Trimble]. \n• As the architect and team lead, we used [Java], [Bash], [GitHub], [Linux], and  [JBoss] message-oriented middleware platform, [Sybase Anywhere] for the client/server based database, and [Windows Mobile] running on ruggedized mobile devices.",
    "Skills": "Bash, Business Requirements, Data Architecture, Data Modeling, Database Design, Databases, DevOps, Front-End, Full-Stack, Git, GitHub, Java, JavaScript/HTML/CSS, Leadership, Linux, Microsoft Excel, Microsoft Project, Presentation Skills, Project Risk, REST APIs, SDLC, SQL, Stakeholder Management, Strategic Planning, Tech Project Manager, User Acceptance Testing",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.eleven.net/\">[Eleven LLC]</a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[Trimble]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://developers.redhat.com/products/eap/overview\">[JBoss]</a></div>",
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[Sybase Anywhere]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/Windows_Mobile_5.0\">[Windows Mobile]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.eleven.net\">http://www.eleven.net</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://developers.redhat.com/products/eap/overview\">http://developers.redhat.com/products/eap/overview</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://en.wikipedia.org/wiki/Windows_Mobile_5.0\">http://en.wikipedia.org/wiki/Windows_Mobile_5.0</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "122": "REST APIs",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "role": "Senior Architect",
    "employer": "Intrusic Cybersecurity LLC",
    "start": "2005-02-01",
    "end": "2006-02-01",
    "z-index": "2",
    "Description": "• [Intrusic LLC] built real-time network monitoring systems that identified external and internal network intrusion attempts\n• As a Sierra Vista Group architech, I helped design and develop an approach for buffering live streaming network traffic for asynchronous package processing. \n• Used [Linux], [C programming language], and [Visio].",
    "Skills": "Bash, Business Requirements, Data Architecture, Data Modeling, Database Design, Databases, DevOps, Git, GitHub, Leadership, Linux, Microsoft Excel, Microsoft Project, Presentation Skills, Project Risk, SDLC, SQL, Stakeholder Management, Strategic Planning, Tech Project Manager, User Acceptance Testing",
    "references": [
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[Intrusic LLC]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.debian.org/\">[Linux]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.cprogramming.com/books/ritchie.html\">[C programming language]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software\">[Visio]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.debian.org\">http://www.debian.org</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.cprogramming.com/books/ritchie.html\">http://www.cprogramming.com/books/ritchie.html</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software\">http://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "78": "Git",
      "79": "GitHub",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "role": "Project Manager / Technical Lead ",
    "employer": "AMI Entertainment Network, LLC",
    "start": "2004-02-01",
    "end": "2005-02-01",
    "z-index": "2",
    "Description": "•  AMI http://amientertainment.com was the internet-music distribution incarnation of Rowe International.  \n•  As a Sierra Vista Group project manager and technical lead, I helped design and implement their system for making monthly ACH royalty payments to music copyright owners for mechanical and performance licensing rights.\n•  Used [FileMaker Pro], [Bash], [Linux], [HTML], [CSS], [JavaScript], [Java], and [Visio].",
    "Skills": "Bash, Business Requirements, Data Architecture, Data Modeling, Database Design, Databases, DevOps, Front-End, Full-Stack, Git, GitHub, Java, JavaScript/HTML/CSS, Leadership, Linux, Microsoft Excel, Microsoft Project, Presentation Skills, Project Risk, REST APIs, SDLC, SQL, Stakeholder Management, Strategic Planning, Tech Project Manager, User Acceptance Testing",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.claris.com/filemaker/\">[FileMaker Pro]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software\">[Visio]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://amientertainment.com\">http://amientertainment.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.claris.com/filemaker/\">http://www.claris.com/filemaker/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software\">http://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "122": "REST APIs",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "role": "Project Manager / Technical Lead ",
    "employer": "Rowe Entertainment (and Internet Jukeboxes)",
    "start": "2003-03-01",
    "end": "2004-02-01",
    "z-index": "2",
    "Description": "•  [Rowe International] was the leading manufacturer of music jukeboxes. \n•  Sierra Vista Group was consulted to assess their available technologies and create a plan to build their back-end systems to let them become a leading provider of internet-based music.\n•  As project manager and technical lead created the project plan and led the development of a full-stack web application used by  jukebox owners and Rowe sales and marketing.\n•  Used [Java], [Bash], [Linux], [HTML], [CSS], [JavaScript], [ObjectDesign], [MySQL], and [Adobe Photoshop].",
    "Skills": "Bash, Business Requirements, Data Architecture, Data Modeling, Database Design, Databases, DevOps, Front-End, Full-Stack, Git, GitHub, Java, JavaScript/HTML/CSS, Leadership, Linux, Microsoft Excel, Microsoft Project, Presentation Skills, Project Risk, REST APIs, SDLC, SQL, Stakeholder Management, Strategic Planning, Tech Project Manager, User Acceptance Testing",
    "references": [
      "<div class=\"anchor-ref-not-found\"><a href=\"\">[Rowe International]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://object.design/\">[ObjectDesign]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.mysql.com/\">[MySQL]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.adobe.com/products/photoshop.html\">[Adobe Photoshop]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://object.design/\">http://object.design/</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.mysql.com\">http://www.mysql.com</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://www.adobe.com/products/photoshop.html\">http://www.adobe.com/products/photoshop.html</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "122": "REST APIs",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "role": "Architectural 3-D Modeler",
    "employer": "Autodesk",
    "start": "1996-05-01",
    "end": "1996-07-01",
    "z-index": "1",
    "Description": "Used my own photometric modeling software to reconstruct textured 3-D models of signature kitchens from uncalibrated camera views. Models were used in \"Picture-This Kitchens\", Autodesk's first commercial product for home design.",
    "Skills": "Bash",
    "references": [],
    "job-skills": {
      "44": "Bash"
    }
  }
];