export const jobs = [
  {
    "employer": "Adobe",
    "role": "Senior Data Engineer ",
    "start": "2025-03-03",
    "end": "CURRENT_DATE",
    "Description": "Tuned automated remediation processes used to improve the quality and security of data.\n• Developed tools for cross environment testing and remote debugging of Kubernetes workflows.\n• AWS architecture focused on providing high-availability, rreliability, and scalability.",
    "references": [],
    "job-skills": {
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "78": "Git",
      "79": "GitHub",
      "80": "GitHub Actions",
      "83": "Infrastructure Monitoring",
      "87": "Jenkins",
      "88": "Jira",
      "118": "Python",
      "122": "REST APIs",
      "128": "Scrum",
      "129": "SDLC",
      "153": "Unit Testing"
    }
  },
  {
    "employer": "Spexture",
    "role": "Senior Data Engineer ",
    "start": "2024-08-15",
    "end": "2025-02-15",
    "Description": "• Designed and implemented an end-to-end CI/CD pipeline using a target-based architecture to optimize model deployment. \nAutomated multi-environment infrastructure provisioning and credential management via Hashicorp Terraform and Vault.\n• Deployed PySpark SQL Docker containers on an EKS-managed Kubernetes cluster to enhance resource utilization and scalability for data processing workloads.\n• Ensured system transparency using real-time monitoring solutions and dashboards with Amazon Managed Grafana.\n• Utilized AWS Glue and PySpark for data ingress, cleansing, versioning, and lineage tracking, maintaining data integrity and regulatory compliance for securi",
    "references": [],
    "job-skills": {
      "44": "Bash",
      "49": "CI/CD",
      "70": "DevOps",
      "80": "GitHub Actions",
      "82": "Hashicort Vault",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "106": "Node.js",
      "118": "Python",
      "120": "React",
      "125": "Schema Validation",
      "153": "Unit Testing"
    }
  },
  {
    "employer": "Fannie Mae",
    "role": "Senior Data Engineer ",
    "start": "2024-02-17",
    "end": "2024-06-27",
    "Description": "• Extensive work with SQL, AWS Redshift, Glue, Airflow, S3, IAM, Lambda, REST, SNS, and dbt\n• Created dbt-validated SQL code for data cleansing and data lake ingestion \n• Used Amazon Glue to track schema changes and revise Redshift external views\n• Created custom views required for analysis and reporting in Redshift\n• Documented processes to build, test, and deploy data pipeline components for in-house ETL framework",
    "references": [],
    "job-skills": {
      "6": "Apache Airflow",
      "8": "Application Migrations",
      "9": "Application Monitoring",
      "15": "AWS CloudWatch",
      "28": "AWS IAM",
      "31": "AWS Lambda",
      "34": "AWS Redshift",
      "36": "AWS S3 Standard",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "58": "Data Catalog",
      "61": "Data Engineering",
      "66": "Databases",
      "67": "Date Partitioning",
      "70": "DevOps",
      "73": "Docker",
      "74": "Docker Compose",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "92": "KPI",
      "95": "Linux",
      "101": "Microsoft Excel",
      "118": "Python",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "141": "SQL",
      "153": "Unit Testing"
    }
  },
  {
    "employer": "The Cigna Group",
    "role": "Senior Data Engineer ",
    "start": "2023-05-01",
    "end": "2023-12-17",
    "Description": "• As a senior data engineer in the data cyber security team of the Cigna Group created a [REST API] using [Postman], [Bash], [Linux], and [OpenAPI] for pulling credentials from CyberArk using [OpenSSL] with mutual TLS SSL authentication via [API Gateway]. \n•  Migrated a suite of legacy [ETL][data pipeline] [Python] elements running on the [Unity IoC platform] with [PostgreSQL] and [S3] to pull credentials from the [CyberArk] identity service at runtime rather than using Fernet encrypted local files. \n•  Upgraded [GitHub] apps to use Jenkins [CI/CD pipeline] for build, applying software and cyber-security code checks, and on-prem server installation.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.thecignagroup.com/\">[Cigna Group]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.cyberark.com/\">[CyberArk]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.solace.com/Security/Two-Way-SSL-Authentication.htm\">[mutual TLS SSL authentication]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://cryptography.io/en/latest/fernet/\">[Fernet]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.aws.amazon.com/apigateway/\">[Jenkins]</a></div>"
    ],
    "job-skills": {
      "6": "Apache Airflow",
      "8": "Application Migrations",
      "9": "Application Monitoring",
      "15": "AWS CloudWatch",
      "27": "AWS Glue",
      "28": "AWS IAM",
      "30": "AWS KMS",
      "31": "AWS Lambda",
      "34": "AWS Redshift",
      "36": "AWS S3 Standard",
      "38": "AWS Secrets Manager",
      "42": "AWS Step Functions",
      "44": "Bash",
      "49": "CI/CD",
      "54": "Cyber Security",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "73": "Docker",
      "74": "Docker Compose",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "92": "KPI",
      "95": "Linux",
      "101": "Microsoft Excel",
      "118": "Python",
      "122": "REST APIs",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "141": "SQL",
      "153": "Unit Testing"
    }
  },
  {
    "employer": "Warner Brothers",
    "role": "Senior Data Engineer ",
    "start": "2022-09-01",
    "end": "2023-05-01",
    "Description": "• As a senior data engineer in the analytics team of Warner Brothers Division, implemented high-volume [ETL] [data pipeline] [integrations] transforming and sharing  game telemetry and [user PII data] between WB-distributed consumer games and [marketing service platforms] via Segment customer data platform using Kafka, [Amazon S3], Redshift, and Apache Airflow. \n• Employed [Python], [GitHub], [Bash], [Linux], Amazon Glue and Apache Airflow for external [3rd-party integrations] and internal dev-ops integrations with [Jenkins], [PostgreSQL], DataDog,  ZenDesk. and [Tableau].\n• Integrated with [Google BigQuery](https://cloud.google.com/bigquery using  Apache Airflow, [Amazon S3], and Redshift.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://warnerbrosgames.com/\">[Warner Brothers]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://segment.com/customer-data-platform/\">[Segment customer data platform]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/msk/\">[Kafka]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/redshift/\">[Redshift]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://airflow.apache.org\">[Apache Airflow]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/glue/\">[Amazon Glue]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://airflow.apache.org/\">[Apache Airflow]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.datadoghq.com/\">[DataDog]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://zendesk.com\">[ZenDesk]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/managed-workflows-for-apache-airflow/\">[Apache Airflow]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/redshift/\">[Redshift]</a></div>"
    ],
    "job-skills": {
      "6": "Apache Airflow",
      "7": "Apache Kafka",
      "8": "Application Migrations",
      "9": "Application Monitoring",
      "15": "AWS CloudWatch",
      "28": "AWS IAM",
      "31": "AWS Lambda",
      "34": "AWS Redshift",
      "36": "AWS S3 Standard",
      "42": "AWS Step Functions",
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "60": "Data Dog",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "81": "Google BigQuery",
      "83": "Infrastructure Monitoring",
      "87": "Jenkins",
      "88": "Jira",
      "92": "KPI",
      "95": "Linux",
      "97": "Martech",
      "101": "Microsoft Excel",
      "103": "New Relic",
      "118": "Python",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "141": "SQL",
      "143": "Statistical Data Analysis",
      "153": "Unit Testing"
    }
  },
  {
    "employer": "Angel Studios",
    "role": "Senior Data Engineer ",
    "start": "2021-11-01",
    "end": "2022-09-01",
    "Description": "• Senior data engineer for Angel Studios, a streaming media service that offers family-friendly entertainment that amplifies light, with titles including The Chosen, Dry Bar Comedy, and Tuttle Twins.\n• Used [Python], [GitHub], [Pandas], [Numpy], [Keras], [Bash], [Linux], [PostgreSQL], and Jupyter to build and tune hyperparameters of a convolutional neural network with [supervised learning] on Amazon Sagemaker to classify movie frames from episodic programs stored in Amazon S3. \n• Built web client apps using [Python] with Postman that made [REST] requests to pull monthly usage data from various web marketing partners like FaceBook Marketing, Google Play , and Vimeo. \n• Worked with Segment customer data platform, [Excel], and [Tableau] to create scheduled reports for the company's sales and finance teams.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.angel.com/home\">[Angel Studios]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://jupyter.org/\">[Jupyter]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://towardsdatascience.com/a-comprehensive-guide-to-convolutional-neural-networks-the-eli5-way-3bd2b1164a53\">[convolutional neural network]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/pm/sagemaker/\">[Amazon Sagemaker]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/s3/storage-classes\">[Amazon S3]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.postman.com/\">[Postman]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.quora.com/What-is-Facebook-Marketing-1\">[FaceBook Marketing]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://play.google/howplayworks/\">[Google Play]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://vimeo.com/\">[Vimeo]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://segment.com/customer-data-platform/\">[Segment customer data platform]</a></div>"
    ],
    "job-skills": {
      "5": "Ansible",
      "10": "Applied Machine Learning",
      "37": "AWS SageMaker",
      "44": "Bash",
      "49": "CI/CD",
      "50": "CNN",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "89": "Jupyter",
      "91": "Keras",
      "92": "KPI",
      "95": "Linux",
      "96": "Machine Learning",
      "98": "MatPlotLib",
      "101": "Microsoft Excel",
      "107": "numpy",
      "110": "Pandas",
      "118": "Python",
      "119": "PyTorch",
      "121": "Regularization",
      "128": "Scrum",
      "129": "SDLC",
      "143": "Statistical Data Analysis",
      "145": "Supervised Classification",
      "146": "Supervised Regression",
      "147": "Tableau",
      "153": "Unit Testing"
    }
  },
  {
    "employer": "Data Laboratory / Greenseed",
    "role": "Senior Data Engineer ",
    "start": "2020-11-01",
    "end": "2021-11-01",
    "Description": "• As a senior software engineer for Data Laboratory, an internet company that provides daily lead reports for independent real-estage agents world-wide, I  [containerized] legacy web applications using [Bash], [Linux], [GitHub], Docker and Amazon Secrets Manager. \n• Updated legacy web apps using [Bash], [Linux], [HTML], [CSS], [JavaScript], [PostgreSQL], [NGINX], and [OpenSSL].\n• Documented existing data architecture as ERDs using DBeaver Enterprise.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.docker.com/\">[Docker]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/secrets-manager/\">[Amazon Secrets Manager]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.lucidchart.com/pages/er-diagrams\">[ERDs]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://dbeaver.com/dbeaver-enterprise/\">[DBeaver Enterprise]</a></div>"
    ],
    "job-skills": {
      "13": "AWS CloudFormation",
      "15": "AWS CloudWatch",
      "19": "AWS EC2",
      "20": "AWS ECR",
      "21": "AWS ECS",
      "22": "AWS EFS",
      "23": "AWS EKS",
      "26": "AWS Fargate",
      "28": "AWS IAM",
      "31": "AWS Lambda",
      "36": "AWS S3 Standard",
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "59": "Data Cleansing",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "73": "Docker",
      "74": "Docker Compose",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "92": "KPI",
      "93": "Kubernetes",
      "95": "Linux",
      "100": "Mentoring",
      "101": "Microsoft Excel",
      "114": "PostgreSQL",
      "118": "Python",
      "122": "REST APIs",
      "128": "Scrum",
      "129": "SDLC",
      "141": "SQL",
      "149": "Tech Project Manager",
      "150": "Terraform",
      "153": "Unit Testing"
    }
  },
  {
    "employer": "NuSkin",
    "role": "Senior Full-Stack Developer ",
    "start": "2019-11-01",
    "end": "2020-11-01",
    "Description": "• As a senior full stack developer for [NuSkin](https://www.nuskin.com/us/en/, an international company known for its excellent  skin and beauty products I created new Vue.js, Nuxt, and Vuetify components using [Bash], [Linux], [GitHub], [NodeJS], [HTML] and [CSS].  \n• Internationalized content using Adobe Experience Cloud.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://vuejs.org/\">[Vue.js]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://nuxt.com/\">[Nuxt]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://vuetifyjs.com/en/\">[Vuetify]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://business.adobe.com/\">[Adobe Experience Cloud]</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "61": "Data Engineering",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "78": "Git",
      "79": "GitHub",
      "87": "Jenkins",
      "88": "Jira",
      "95": "Linux",
      "101": "Microsoft Excel",
      "106": "Node.js",
      "113": "Plotly",
      "123": "SaaS",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "153": "Unit Testing",
      "155": "Vue.js"
    }
  },
  {
    "employer": "SeniorLink / Vela",
    "role": "Senior Data Engineer ",
    "start": "2017-03-01",
    "end": "2019-11-01",
    "Description": "• As a senior data engineer for SeniorLink's Vela project a homeservices support platform, helped create ETL processes using Amazon Kinesis, [Python], PySpark, and Amazon Data Pipeline to load structured event data from [PostgreSQL] databases into Redshift. \n• Saved data to [Amazon S3] using [Amazon Kinesis] and triggered Amazon Lambda jobs to aggregate steaming event data into [schema-on-read] file formats, Apache Avro and Apache Parquet.\n• Steered efforts in creating a Data Lake using [PostgreSQL] and FlyWay with [Python] and PySpark pre-processing on [EC2 instances] using shared Amazon EFS for staged storage.\n• Used streaming event messages queued in RabbitMQ and [Amazon Kinesis] to build [type-2 slowly changing dimensions] and accumulative facts tables. \n• Designed and implemented a custom star-schema warehouse and [ETL] processes to de-normalize and load data into Redshift data warehouse for BI reporting using Tableau.\n• Test-driven development using [Bash], [Linux], [Python], [PyCharm], [PyTest], [Unit-test], [GitHub], [Jira], and Jenkins.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"/static_content/portfolio/Vela-150x126.png\">[Vela project]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/what-is/etl/\">[ETL]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/pm/kinesis/\">[Amazon Kinesis]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://spark.apache.org/\">[PySpark]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/what-is-datapipeline.html\">[Amazon Data Pipeline]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/pm/redshift/\">[Redshift]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.aws.amazon.com/lambda/\">[Amazon Lambda]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://avro.apache.org/\">[Apache Avro]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://parquet.apache.org/\">[Apache Parquet]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/big-data/datalakes-and-analytics/datalakes/\">[Data Lake]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://flywaydb.org/\">[FlyWay]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://spark.apache.org/docs/latest/api/python/index.html\">[PySpark]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://zesty.co/blog/ebs-vs-efs-which-is-right\">[Amazon EFS]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/working-with-rabbitmq.html\">[RabbitMQ]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.databricks.com/glossary/star-schema\">[star-schema warehouse]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/Denormalization\">[de-normalize]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/redshift/\">[Redshift]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.tableau.com/\">[Tableau]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.pluralsight.com/blog/software-development/tdd-vs-bdd\">[Test-driven development]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.jenkins.io/\">[Jenkins]</a></div>"
    ],
    "job-skills": {
      "9": "Application Monitoring",
      "15": "AWS CloudWatch",
      "16": "AWS DataPipeline",
      "18": "AWS EBS",
      "19": "AWS EC2",
      "21": "AWS ECS",
      "22": "AWS EFS",
      "25": "AWS EMR",
      "28": "AWS IAM",
      "29": "AWS Kinesis",
      "31": "AWS Lambda",
      "33": "AWS RDS",
      "34": "AWS Redshift",
      "36": "AWS S3 Standard",
      "40": "AWS SNS",
      "41": "AWS SQS",
      "44": "Bash",
      "49": "CI/CD",
      "55": "Daily Scrum",
      "56": "Data Architecture",
      "61": "Data Engineering",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "67": "Date Partitioning",
      "69": "Denormalization",
      "70": "DevOps",
      "71": "Dimensional Modeling",
      "75": "ETL",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "87": "Jenkins",
      "88": "Jira",
      "95": "Linux",
      "101": "Microsoft Excel",
      "114": "PostgreSQL",
      "117": "PySpark EMR",
      "118": "Python",
      "122": "REST APIs",
      "124": "Schema Evolution",
      "125": "Schema Validation",
      "128": "Scrum",
      "129": "SDLC",
      "137": "Sprint Planning",
      "138": "Sprint Retrospective",
      "139": "Sprint Review",
      "140": "Sprints",
      "144": "Strategic Planning",
      "147": "Tableau",
      "153": "Unit Testing",
      "154": "Visio"
    }
  },
  {
    "employer": "BigR.io",
    "role": "Senior Back-End Engineer ",
    "start": "2016-12-01",
    "end": "2017-03-01",
    "Description": "• As a senior software engineer at BigR.io I used [Amazon microservices] for custom voice-based [natural language processing] applications.\n• Used Apache ActiveMQ, Swagger, [JSON], Jackson, AOP, [Eclipse], [Maven], [GitHub], [Jira], [PostgreSQL], and [Jenkins].\n• [Java], [J2EE], [Servlets], [Spring], [SpringBoot], [JAX-RS], [Bash], [Linux], [JUnit], [JMeter], and [JProfile]",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"/static_content/portfolio/Bigr.io_-150x106.png\">[BigR.io]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://activemq.apache.org/\">[Apache ActiveMQ]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://swagger.io/\">[Swagger]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"url\">[Jackson]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.baeldung.com/spring-aop\">[AOP]</a></div>"
    ],
    "job-skills": {
      "28": "AWS IAM",
      "85": "Java",
      "122": "REST APIs",
      "134": "Spring",
      "135": "Spring Boot"
    }
  },
  {
    "employer": "ClipFile, LLC",
    "role": "Technical Lead / Co-Founder ",
    "start": "2011-02-01",
    "end": "2016-12-01",
    "Description": "• Co-founded ClipFile, a company that envisioned building a web destination where users could easily record and share their favorite pieces of content like facts, authored stories, quotes, articles, chapters, or personal thoughts, as a way of concretely defining their personal mindset.\n• Implemented fuzzy matching, word clustering, semantic similarity scores, and collaborative filtering to help users find content that matched or differed from thieir own mindset.\n• Launched a novel [SaaS] using [Amazon Web Services] that let individuals and content creators search and share mindsets.\n• Conceptualized patented technology by designing and implementing a fuil-stack consumer-facing content management system that supported tuned matching among selected attributes.\n• [Java], [J2EE], [JSP], [Servlets], [Spring], [Amazon services], [JavaScript], [JQuery], [HTML], [CSS], [JUnit], [JMeter], [JProfile].\n• Utilized [REST], [Swagger], Apache Shiro, Eclipse IDE, Apache Maven, Apache Ant, [GitHub], [Hibernate], Amazon SimpleDB, Linux, Apache Tomcat, [Bash], [Linux], Jetty, and Spring MVC.\n• Served as co-founder and co-authored four patents.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://sourcesofinsight.com/what-is-mindset/\">[mindset]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"/static_content/portfolio/clipfile-infrastructure-150x150.png\">[ClipFile]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://nanonets.com/blog/fuzzy-matching-fuzzy-logic/\">[fuzzy matching]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.ilc.cnr.it/EAGLES96/rep2/node37.html#:~:text=Word%20clustering%20is%20a%20technique,to%20information%20retrieval%20and%20filtering.\">[word clustering]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://towardsdatascience.com/semantic-similarity-using-transformers-8f3cb5bf66d6\">[semantic similarity scores]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.hindawi.com/journals/aai/2009/421425/\">[collaborative filtering]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://shiro.apache.org/\">[Apache Shiro]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.eclipse.org/home/whatis/\">[Eclipse IDE]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://maven.apache.org/what-is-maven.html\">[Apache Maven]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://ant.apache.org/\">[Apache Ant]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://aws.amazon.com/simpledb/\">[Amazon SimpleDB]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.centos.org/\">[Linux]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://tomcat.apache.org/\">[Apache Tomcat]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://projects.eclipse.org/projects/rt.jetty\">[Jetty]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://docs.spring.io/spring-framework/reference/web/webmvc.html\">[Spring MVC]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.freepatentsonline.com/y2013/0325870.html\">[four patents]</a></div>"
    ],
    "job-skills": {
      "15": "AWS CloudWatch",
      "17": "AWS DynamoDB",
      "19": "AWS EC2",
      "22": "AWS EFS",
      "24": "AWS Elastic Beanstalk",
      "28": "AWS IAM",
      "31": "AWS Lambda",
      "32": "AWS Load Balancer",
      "35": "AWS Route 53",
      "36": "AWS S3 Standard",
      "39": "AWS SimpleDB",
      "40": "AWS SNS",
      "41": "AWS SQS",
      "43": "AWS VPC",
      "44": "Bash",
      "45": "Bayesian Clustering",
      "51": "Collaborative Filtering",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "72": "Dimensionality Reduction",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "86": "JavaScript/HTML/CSS",
      "90": "K-means clustering",
      "95": "Linux",
      "96": "Machine Learning",
      "100": "Mentoring",
      "101": "Microsoft Excel",
      "105": "nltk",
      "111": "Pattern Recognition",
      "122": "REST APIs",
      "123": "SaaS",
      "129": "SDLC",
      "131": "Sentiment Analysis",
      "134": "Spring",
      "135": "Spring Boot",
      "136": "Spring MVC",
      "137": "Sprint Planning",
      "141": "SQL",
      "144": "Strategic Planning",
      "148": "Tech Product Manager",
      "154": "Visio"
    }
  },
  {
    "employer": "Sierra Vista Group, LLC",
    "role": "Lead Solutions Architect / Co-Founder ",
    "start": "2002-11-01",
    "end": "2011-02-01",
    "Description": "• Co-founded a finance and technology boutique called Sierra Vista Group that delivered support in planning and proposing effective IT strategies for key clients in several industries. \n• Performed various services, including system and architecture assessment and solutions design, to ensure the smooth running of technical projects.\n• Managed project schedules and technical specifications to match business requirements within contractual budget constraints. \n• Identified opportunities for potential clients requiring expertise in product development, software engineering, and data modeling. Negotiated and communicated with c-level client management regarding project milestone agreements.\n• Increased ROI for each client’s project by hiring and managing contractors to deliver custom software solutions.\n• Delivered high-level leadership and guidance to a team of software engineering consultants for several projects to accelerate operational excellence.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://6sense.com/company/sierra-vista-group-llc/5ba8a5247c8666394376fc4f\">[Sierra Vista Group]</a></div>"
    ],
    "job-skills": {
      "15": "AWS CloudWatch",
      "28": "AWS IAM",
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "100": "Mentoring",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "123": "SaaS",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "148": "Tech Product Manager",
      "152": "User Acceptance Testing",
      "154": "Visio"
    }
  },
  {
    "employer": "One Call Care Management (formerly MSC )",
    "role": "Project Manager / Technical Lead ",
    "start": "2007-12-01",
    "end": "2010-08-01",
    "Description": "• MSC, now called OneCall, is a leading workers compensation services company. \n• As project manager and technical lead for this Sierra Vista Group project, I presented fixed schedule-fixed budget project proposals to C-level executives to add features to their legacy call center system used by 10 different healthcare divisions. \n• Interviewed stakeholders to create functional requirements and technical spefications for each stage of development.\n• Worked with development team to create work plan, assign tasks.\n• Oversaw quality assurance and customer approval testing.\n• Used the MS Office suite of business apps a well as MS Visio.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://onecallcm.com/\">[OneCall]</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "78": "Git",
      "79": "GitHub",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "employer": "Eleven LLC / Trimble Mobile",
    "role": "Senior Architect ",
    "start": "2006-02-01",
    "end": "2007-12-01",
    "Description": "• Eleven LLC built mobile apps used by beverage industry distributors to help manage placement  of their products in the shelves and coolers in Resume locations. The work done by the Sierra Vista Group was instrumental in their company being acquired by Trimble. \n• As the architect and team lead, we used [Java], [Bash], [GitHub], [Linux], and  JBoss message-oriented middleware platform, Sybase Anywhere for the client/server based database, and Windows Mobile running on ruggedized mobile devices.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.eleven.net/\">[Eleven LLC]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://help.trimblegeospatial.com/TMM/Home.htm\">[Trimble]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://developers.redhat.com/products/eap/overview\">[JBoss]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://texas.gs.shi.com/Product/30451452/Sybase-SQL-Anywhere-Advanced-Edition\">[Sybase Anywhere]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/Windows_Mobile_5.0\">[Windows Mobile]</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "122": "REST APIs",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "employer": "Intrusic Cybersecurity LLC",
    "role": "Senior Architect",
    "start": "2005-02-01",
    "end": "2006-02-01",
    "Description": "• Intrusic LLC built real-time network monitoring systems that identified external and internal network intrusion attempts\n• As a Sierra Vista Group architech, I helped design and develop an approach for buffering live streaming network traffic for asynchronous package processing. \n• Used Linux, C programming language, and Visio.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.crunchbase.com/organization/intrusic\">[Intrusic LLC]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.debian.org/\">[Linux]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.cprogramming.com/books/ritchie.html\">[C programming language]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software\">[Visio]</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "78": "Git",
      "79": "GitHub",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "employer": "AMI Entertainment Network, LLC",
    "role": "Project Manager / Technical Lead ",
    "start": "2004-02-01",
    "end": "2005-02-01",
    "Description": "•  AMI  was the internet-music distribution incarnation of Rowe International.  \n•  As a Sierra Vista Group project manager and technical lead, I helped design and implement their system for making monthly ACH royalty payments to music copyright owners for mechanical and performance licensing rights.\n•  Used FileMaker Pro, [Bash], [Linux], [HTML], [CSS], [JavaScript], [Java], and Visio.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.claris.com/filemaker/\">[FileMaker Pro]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.microsoft.com/en-us/microsoft-365/visio/flowchart-software\">[Visio]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://amientertainment.com/\">https://amientertainment.com/</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "122": "REST APIs",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "employer": "Rowe Entertainment (and Internet Jukeboxes)",
    "role": "Project Manager / Technical Lead ",
    "start": "2003-03-01",
    "end": "2004-02-01",
    "Description": "•  Rowe International was the leading manufacturer of music jukeboxes. \n•  Sierra Vista Group was consulted to assess their available technologies and create a plan to build their back-end systems to let them become a leading provider of internet-based music.\n•  As project manager and technical lead created the project plan and led the development of a full-stack web application used by  jukebox owners and Rowe sales and marketing.\n•  Used [Java], [Bash], [Linux], [HTML], [CSS], [JavaScript], ObjectDesign, MySQL, and Adobe Photoshop.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://pitchbook.com/profiles/company/13178-08\">[Rowe International]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://object.design/\">[ObjectDesign]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.mysql.com/\">[MySQL]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.adobe.com/products/photoshop.html\">[Adobe Photoshop]</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "46": "Business Requirements",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "102": "Microsoft Project",
      "115": "Presentation Skills",
      "116": "Project Risk",
      "122": "REST APIs",
      "129": "SDLC",
      "141": "SQL",
      "142": "Stakeholder Management",
      "144": "Strategic Planning",
      "149": "Tech Project Manager",
      "152": "User Acceptance Testing"
    }
  },
  {
    "employer": "HomePorfolio, Inc.",
    "role": "Technical Lead / Co-Founder ",
    "start": "1998-02-01",
    "end": "2002-11-01",
    "Description": "• As co-founder and CTO, designed and led the development of a public website used by discerning home designers and builders called HomePortfolio. \n• Hired a staff of  10 software and databases developers. \n• Worked with data acquisition team to scan and tag over 700,000 premium home design products from over 2,000 manufactures and vendors.\n• Designed datamodel and data entry tools for category-specific product attribution. \n• Helped extended the business model to provide online product selection tools for participating vendors and manufacturers.\n• Instrumental in raising over $70M in venture capital. \n• Used [Oracle], [ATG Dyanamo]( https://docs.oracle.com/cd/E24152_01/Platform.10-1/ATGPersBusinessGuide/html/s0102dynamoapplicationframework01.html), [Java], Akamai, WebTrends, [FileMakerPro], ImageMagik, [Bash], [Linux], [HTML], [JavaScript], [CSS], and Omnigraffle for data modeling and workflow designs.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://www.akamai.com/\">[Akamai]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://HomePortfolio/\">[HomePortfolio]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.webtrends.com/\">[WebTrends]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://imagemagick.org/index.php\">[ImageMagik]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.omnigroup.com/omnigraffle\">[Omnigraffle]</a></div>"
    ],
    "job-skills": {
      "3": "Akamai",
      "4": "Algorithms",
      "9": "Application Monitoring",
      "11": "ATG Dynamo",
      "15": "AWS CloudWatch",
      "28": "AWS IAM",
      "44": "Bash",
      "56": "Data Architecture",
      "64": "Data Modeling",
      "65": "Database Design",
      "66": "Databases",
      "70": "DevOps",
      "76": "Front-End",
      "77": "Full-Stack",
      "78": "Git",
      "79": "GitHub",
      "85": "Java",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "101": "Microsoft Excel",
      "109": "Oracle Database",
      "129": "SDLC",
      "132": "SEO",
      "141": "SQL",
      "156": "Director"
    }
  },
  {
    "employer": "BuildingBlocks, LLC",
    "role": "Lead Software Developer ",
    "start": "1996-06-01",
    "end": "1998-02-01",
    "Description": "• As lead software developer, built a CD-ROM-based home design application for selecting premium home design products for previewing in the context of images of any household rooms. \n• Built the prototype using Adobe Photoshop and Macromedia Director.\n• Built the actual application using using [Bash], [Linux], [Java] and Marimba Bongo widget layout tool.\n• Updates for the self-updating application were delivered over the internet using Marimba Castanet push-technology.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://macromedia.fandom.com/wiki/Macromedia_Director\">[Macromedia Director]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.thriftbooks.com/w/official-marimba-guide-to-bongo_danny-goodman/2574616/#edition=58026223&idiq=42367912\">[Marimba Bongo]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.infoworld.com/article/2076707/marimba-launches-new-castanet-with-a-less-java-centric-focus.html\">[Marimba Castanet]</a></div>"
    ],
    "job-skills": {
      "86": "JavaScript/HTML/CSS",
      "156": "Director"
    }
  },
  {
    "employer": "Autodesk",
    "role": "3D Scene Reconstruction Engineer",
    "start": "1996-04-01",
    "end": "1996-08-01",
    "Description": "• Used self-authored photogrammetric scene reconstruction software to build textured 3D models of interior architecture from one uncalibrated image per room.\n• Reconstructed kitchen models are featured in Autodesk's \"Picture This Kitchen\" product, allowing users to visualize each room with different flooring, cabinetry, appliances, lighting, and walls from a palette of options.",
    "references": [],
    "job-skills": {
      "44": "Bash"
    }
  },
  {
    "employer": "MIT Media Lab",
    "role": "Ph.D. Media Arts & Science",
    "start": "1990-09-01",
    "end": "1997-04-01",
    "Description": "•\tDoctor of Philosopy degree, MIT, Cambridge, Massachusettes\n•\tMedia Laboratory, Media Arts and Sciences\n•\tTook courses in machine vision, signals and systems, digital signal processing, and stochastics.\n•\tHelped build the operating system for the Cheops multi-processor system used for digital video research and for holographic video\n•\t“Vision-assisted modeling for model-based video representations”, (Ph.D. Dissertation) MIT, Program in Media Arts & Sciences, 1997\n•\t“Semiautomatic 3-D Model Extraction from Uncalibrated 2-D Camera Views.” S. Becker & V. M. Bove, Jr., Proc. SPIE Image Synthesis, 2410, 1995, pp. 447-461.\n•\t“Semiautomatic Scene Modeling From 2-D Views with Partially Known Structure.” Shawn Becker, MIT Media Lab Reports, 1995\n•\t“Semiautomatic Camera Lens Calibration from Partially Known Structure”, Shawn Becker, MIT Media Lab Reports, 1994\n•\t“Formulating a scene probability equation to differentiate the effects of shape & albedo on image brightness.” Shawn Becker, MIT Media Lab Reports, 1994\n•\t“Computation of some projective-chirplet-transform & metaplectic-chirplet-transform subspaces, with applications in image processing.” Steve Mann & Shawn Becker, DSP World Symposium, Boston, Massachusetts, November 1992.\n• [C programming language], [TclTk], [X11], [HTML], [JavaScript],[CSS],[XMotif], [Bash], [Linux]",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"/static_content/portfolio/MIT-logo.png\">[MIT]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"http://alumni.media.mit.edu/~wad/cheops_CSVT/cheops.html\">[Cheops multi-processor system]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://dspace.mit.edu/handle/1721.1/29123\">[“Vision-assisted modeling for model-based video representations”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.media.mit.edu/publications/semiautomatic-3-d-model-extraction-from-uncalibrated-2-d-camera-views-2/\">[“Semiautomatic 3-D Model Extraction from Uncalibrated 2-D Camera Views.”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.researchgate.net/publication/2668457_Formulating_a_Scene_Probability_Equation_to_Differentiate_the_Effects_of_Shape_and_Albedo_on_Image_Brightness\">[“Formulating a scene probability equation to differentiate the effects of shape & albedo on image brightness.”]</a></div>"
    ],
    "job-skills": {
      "4": "Algorithms",
      "10": "Applied Machine Learning",
      "44": "Bash",
      "45": "Bayesian Clustering",
      "47": "C",
      "52": "Computer Vision",
      "76": "Front-End",
      "77": "Full-Stack",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "96": "Machine Learning",
      "111": "Pattern Recognition",
      "116": "Project Risk",
      "129": "SDLC",
      "143": "Statistical Data Analysis",
      "146": "Supervised Regression",
      "154": "Visio"
    }
  },
  {
    "employer": "Cimmetrix Robotics LLC",
    "role": "Full Stack Developer",
    "start": "1988-06-01",
    "end": "1989-09-01",
    "Description": "• Front-end software developer of a reverse kinametics path planning system for multi-axis industrial robots for Cimmetrix.\n• Technologies used include [Bash], [Linux], [C programming language], Bash, [X11] , Xt toolkit intrinsics, Silicon Graphics Irix, and HP-UX.",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"/static_content/portfolio/Cimetrix-PDF-combined-logo-150x100.png\">[Cimmetrix]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/Bourne_shell\">[Bash]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/X_Toolkit_Intrinsics\">[Xt toolkit intrinsics]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/Silicon_Graphics\">[Silicon Graphics Irix]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://en.wikipedia.org/wiki/HP-UX\">[HP-UX]</a></div>"
    ],
    "job-skills": {
      "44": "Bash",
      "47": "C",
      "76": "Front-End",
      "77": "Full-Stack",
      "86": "JavaScript/HTML/CSS",
      "95": "Linux",
      "129": "SDLC"
    }
  },
  {
    "employer": "BYU-CS",
    "role": "MS Computer Science",
    "start": "1987-09-01",
    "end": "1990-09-01",
    "Description": "• Masters of Science degree, BYU, Provo, Utah\nTook all courses required for both bachelors and masters degrees in Computer Science\n• Thesis project “Interactive Measurement of Three-Dimensional Objects Using a Depth Buffer & Linear Probe.” CS MS Thesis, Shawn Becker, William A. Barrett & Dan R. Olsen, ACM Transactions on Graphics, Vol. 10, No. 2, April 1991\n• Top Research Presentation – New Tech Research Conference - BYU – Provo, UT – March 1990\n• “Fast Automated Object Detection Using Signature Parsing.” Tim Heaton; Shawn Becker; Kelley Anderson; William Barrett: Proceedings Volume 1192, Intelligent Robots & Computer Vision VIII: Algorithms & Techniques;  https://doi.org/10.1117/12.969720\n• “Probabilistic Segmentation of Myocardial Tissue by Deterministic Relaxation.” Jerome A. Broekhuijsen, Shawn C. Becker, & William A. Barrett: IEEE Proceedings of Computers in Cardiology, pp. 99-12, Jerusalem, September 1989.\n• “Interactive Measurement of three-Dimensional Cardiac Morphology.” Shawn C Becker, William A Barrett, October 1989, DOI: 10.1109/CIC.1989.130586, Conference: Computers in Cardiology.\n• [C programming language], [Bash], [Linux], [XMotif], and [X11].",
    "references": [
      "<div class=\"anchor-ref\"><a href=\"https://scholarsarchive.byu.edu/cgi/viewcontent.cgi?article=1736&context=facpub\">[“Interactive Measurement of three-Dimensional Cardiac Morphology.”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"/static_content/portfolio/BYU-entrance-150x150.jpg\">[BYU]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://dl.acm.org/doi/pdf/10.1145/108360.108446\">[“Interactive Measurement of Three-Dimensional Objects Using a Depth Buffer & Linear Probe.”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://www.spiedigitallibrary.org/conference-proceedings-of-spie/1192/1/Fast-Automated-Object-Detection-Using-Signature-Parsing/10.1117/12.969720.short\">[“Fast Automated Object Detection Using Signature Parsing.”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"https://scholarsarchive.byu.edu/cgi/viewcontent.cgi?article=1737&context=facpub\">[“Probabilistic Segmentation of Myocardial Tissue by Deterministic Relaxation.”]</a></div>",
      "<div class=\"anchor-ref\"><a href=\"1990\">1990</a></div>"
    ],
    "job-skills": {
      "4": "Algorithms",
      "44": "Bash",
      "47": "C",
      "76": "Front-End",
      "77": "Full-Stack",
      "86": "JavaScript/HTML/CSS",
      "94": "Leadership",
      "95": "Linux",
      "116": "Project Risk",
      "129": "SDLC",
      "154": "Visio"
    }
  }
];