#!/bin/bash

# Converts jobs.xlsx file to a jobs.js file which can be 
# referenced as static content from any html file.
# 
# Details:
# The jobs.xlsx spreadsheet file is converted to a csv file and 
# then to a json file using in2csv and csvjson. These are python 
# utilities that become callable after activating the local 
# python virtual environment using `source venv/bin/activate`.
#
# The  jobs.json file is then used to create the jobs.js file
# using standard unix tools.  The `truncate -s -1 jobs.js`` line 
# removes the trailing newline character added by
# `echo "const jobs = " > jobs.js`
#
# The new jobs.js file is then be referenced from html as any 
# local javascript file using:
#     <script type="text/javascript" src="static_files/jobs.js"></script>
#

source venv/bin/activate
in2csv jobs.xlsx | csvjson > jobs.json
echo "const jobs = " > jobs.js
truncate -s -1 jobs.js
cat jobs.json >> jobs.js
echo ";" >> jobs.js
rm jobs.json
deactivate
echo "done"